### ISSUE TITLE
officially support PyPy

### ISSUE THREAD

**Issue by davidmarin** [Yelp/mrjob#1011]
PyPy is supposed to be about 7x faster than CPython, at least according to [PyPy's benchmarks](http://speed.pypy.org/).

`mrjob`'s tests pass on PyPy already. It looks like all we need to do is look at `platform.python_implementation()`, and if it's `"PyPy"`, choose `pypy` or `pypy3` as the interpreter when running on a remote host, and actually include PyPy in our hand-testing.

**Comment by davidmarin** [comment]
EMR AMIs don't have PyPy installed by default (or a pypy package), so it'd be pretty partial "support" if I just did this. I think it's better to find `bootstrap` and `python_bin` options that make this work, and then make it work automatically.

Portable PyPy binaries might help: https://github.com/squeaky-pl/portable-pypy

**Comment by davidmarin** [comment]
Probably worth looking into why PyPy occasionally raises an `IOError` (broken pipe) instead of `CalledProcessError` in `tests.test_runner.TestInvokeSort.test_bad_sort()`.

**Comment by davidmarin** [comment]
The version-specific `mrjob` binaries should be named e.g. `mrjob-pypy`, `mrjob-pypy3`

**Comment by davidmarin** [comment]
You can get pypy (pypy2, anyway) on Amazon Linux 2015.09, according to: https://aws.amazon.com/blogs/aws/now-available-amazon-linux-ami-2015-09/

**Comment by davidmarin** [comment]
That would give us support back to either 4.2.0 or 4.1.0 (not totally clear which one introduced Amazon Linux 2015.09). Looks like `pypy2` is still on the "preview" repo for 2016.03.

**Comment by davidmarin** [comment]
Seems like ``s3transfer`` doesn't support PyPy3; seeing the following error in my tests:

```
Traceback (most recent call last):
  File "/opt/python/pypy3-2.4.0/lib-python/3/unittest/case.py", line 370, in _executeTestPart
    function()
  File "/opt/python/pypy3-2.4.0/lib-python/3/unittest/loader.py", line 32, in testFailure
    raise exception
ImportError: Failed to import test module: tools.emr.test_terminate_idle_clusters
Traceback (most recent call last):
  File "/opt/python/pypy3-2.4.0/lib-python/3/unittest/loader.py", line 261, in _find_tests
    module = self._get_module_from_name(name)
  File "/opt/python/pypy3-2.4.0/lib-python/3/unittest/loader.py", line 239, in _get_module_from_name
    __import__(name)
  File "/home/travis/build/davidmarin/mrjob/tests/tools/emr/__init__.py", line 17, in <module>
    from mrjob.emr import EMRJobRunner
  File "/home/travis/build/davidmarin/mrjob/mrjob/emr.py", line 60, in <module>
    import boto3.s3.transfer
  File "/home/travis/virtualenv/pypy3-2.4.0/site-packages/boto3/s3/transfer.py", line 127, in <module>
    from s3transfer.exceptions import RetriesExceededError as \
  File "/home/travis/virtualenv/pypy3-2.4.0/site-packages/s3transfer/__init__.py", line 141, in <module>
    import s3transfer.compat
  File "/home/travis/virtualenv/pypy3-2.4.0/site-packages/s3transfer/compat.py", line 47, in <module>
    SOCKET_ERROR = ConnectionError
NameError: name 'ConnectionError' is not defined
```

**Comment by davidmarin** [comment]
Oh, Travis CI is just out-of-date. pypy3 2.4.0, is, in theory, a port of Python 3.2, and may very well lack `ConnectionError` for that reason.

**Comment by davidmarin** [comment]
It seems like it might be difficult to auto-install PyPy on EMR. Amazon Linux used to [tentatively offer PyPy packages](https://aws.amazon.com/blogs/aws/now-available-amazon-linux-ami-2015-09/), but it [no longer does](https://aws.amazon.com/amazon-linux-ami/2018-03-packages/). At the very least, it ought to be a separate ticket.

However, automatically selecting `pypy` or `pypy3` as `python_bin` based on the current version of Python would not be a bad idea at all.

**Comment by davidmarin** [comment]
Got it working on EMR!

First you need to download a package from [Portable PyPy Distribution for Linux](https://github.com/squeaky-pl/portable-pypy#portable-pypy-distribution-for-linux).

Then you add a bootstrap action that un-tars it and symlink to the `pypy` or `pypy3` binary in `/usr/bin` (`/usr/local/bin` doesn't work at bootstrap time). Your `mrjob.conf` looks something like this:

```
runners:
  emr:
    bootstrap:
    - sudo tar xvfj ~/local/path/to/pypy3.6-7.1.1-beta-linux_x86_64-portable.tar.bz2# -C /opt
    - sudo ln -s /opt/pypy3.6-7.1.1-beta-linux_x86_64-portable/bin/pypy3 /usr/bin/pypy3
```
