### ISSUE TITLE
FYI: MRJob job setup fails on MapR 4.x due to bug in their "hadoop fs -mkdir -p"

### ISSUE THREAD

**Issue by dpichard** [Yelp/mrjob#1015]
Just wanted this noted here, since it will bite other MRJob users who are running MapR 4.x.  When MRJob (0.4.3/0.4.4) is making the temporary scratch directory in HDFS, it "fails" because MapR's `hadoop fs -mkdir -p` command feigns a failure if the path ends with a trailing `/`, though it actually ends up making the directory anyway.  I have an open bug with MapR about this issue, will happily update once I hear anything about their fix timeline -- for now I'm going to patch the MRJob package we use in our environment to work around the "failure".

Example output:
```
WRAPPER: # store $PWD
WRAPPER: __mrjob_PWD=$PWD
WRAPPER: 
WRAPPER: # obtain exclusive file lock
WRAPPER: exec 9>/tmp/wrapper.lock.aggregate_feed.dpichard.20150521.145103.481853
WRAPPER: python -c 'import fcntl; fcntl.flock(9, fcntl.LOCK_EX)'
WRAPPER: 
WRAPPER: # setup commands
WRAPPER: {
WRAPPER:   export PYTHONPATH=$__mrjob_PWD/mrjob.tar.gz:$PYTHONPATH
WRAPPER:   export PYTHONPATH=$__mrjob_PWD/cdslite-libs-mapr.tgz:$PYTHONPATH
WRAPPER: } 0</dev/null 1>&2
WRAPPER: 
WRAPPER: # release exclusive file lock
WRAPPER: exec 9>&-
WRAPPER: 
WRAPPER: # run task from the original working directory
WRAPPER: cd $__mrjob_PWD
WRAPPER: "$@"
Making directory maprfs:///TIP/tmp/mrjob-scratch/aggregate_feed.dpichard.20150521.145103.481853/files/ on HDFS
> /opt/mapr/hadoop/hadoop-2.5.1/bin/hadoop version
Using Hadoop version 2.5.1
> /opt/mapr/hadoop/hadoop-2.5.1/bin/hadoop fs -mkdir -p maprfs:///TIP/tmp/mrjob-scratch/aggregate_feed.dpichard.20150521.145103.481853/files/
STDOUT: 2015-05-21 10:51:07,2633 ERROR JniCommon fs/client/fileclient/cc/jni_MapRClient.cc:1306 Thread: 12680 mkdirs failed for /TIP/tmp/mrjob-scratch/aggregate_feed.dpichard.20150521.145103., error 22
STDERR: mkdir: Error: Invalid argument(22), file: , user name: dpichard, ID: 246732
Traceback (most recent call last):
  File "./aggregate_feed.py", line 160, in <module>
    CDS_Aggregate_Feed.run()
  File "/users/dpichard/env-mrjob-release/lib/python2.6/site-packages/mrjob/job.py", line 461, in run
    mr_job.execute()
  File "/users/dpichard/env-mrjob-release/lib/python2.6/site-packages/mrjob/job.py", line 479, in execute
    super(MRJob, self).execute()
  File "/users/dpichard/env-mrjob-release/lib/python2.6/site-packages/mrjob/launch.py", line 151, in execute
    self.run_job()
  File "/users/dpichard/env-mrjob-release/lib/python2.6/site-packages/mrjob/launch.py", line 214, in run_job
    runner.run()
  File "/users/dpichard/env-mrjob-release/lib/python2.6/site-packages/mrjob/runner.py", line 464, in run
    self._run()
  File "/users/dpichard/env-mrjob-release/lib/python2.6/site-packages/mrjob/hadoop.py", line 236, in _run
    self._upload_local_files_to_hdfs()
  File "/users/dpichard/env-mrjob-release/lib/python2.6/site-packages/mrjob/hadoop.py", line 263, in _upload_local_files_to_hdfs
    self._mkdir_on_hdfs(self._upload_mgr.prefix)
  File "/users/dpichard/env-mrjob-release/lib/python2.6/site-packages/mrjob/hadoop.py", line 283, in _mkdir_on_hdfs
    self.invoke_hadoop(['fs', '-mkdir', '-p', path])
  File "/users/dpichard/env-mrjob-release/lib/python2.6/site-packages/mrjob/fs/hadoop.py", line 109, in invoke_hadoop
    raise CalledProcessError(proc.returncode, args)
subprocess.CalledProcessError: Command '['/opt/mapr/hadoop/hadoop-2.5.1/bin/hadoop', 'fs', '-mkdir', '-p', 'maprfs:///TIP/tmp/mrjob-scratch/aggregate_feed.dpichard.20150521.145103.481853/files/']' returned non-zero exit status 1
```

Basic CLI evidence:
```
% /opt/mapr/hadoop/hadoop-2.5.1/bin/hadoop fs -mkdir -p maprfs:///TIP/tmp/mrjob-scratch/test-2
% /opt/mapr/hadoop/hadoop-2.5.1/bin/hadoop fs -mkdir -p maprfs:///TIP/tmp/mrjob-scratch/test-3/
2015-05-21 10:57:00,6418 ERROR JniCommon fs/client/fileclient/cc/jni_MapRClient.cc:1306 Thread: 15525 mkdirs failed for /TIP/tmp/mrjob-scratch/test-3/, error 22
mkdir: Error: Invalid argument(22), file: , user name: dpichard, ID: 246732
% hadoop fs -ls maprfs:///TIP/tmp/mrjob-scratch/       
Found 3 items
drwxr-xr-x   - dpichard tip-users          1 2015-05-21 10:51 maprfs:///TIP/tmp/mrjob-scratch/aggregate_feed.dpichard.20150521.145103.481853
drwxr-xr-x   - dpichard tip-users          0 2015-05-21 10:56 maprfs:///TIP/tmp/mrjob-scratch/test-2
drwxr-xr-x   - dpichard tip-users          0 2015-05-21 10:57 maprfs:///TIP/tmp/mrjob-scratch/test-3
```

**Comment by davidmarin** [comment]
Great, thanks for letting me know. That's really easy to work around (just `.rstrip('/')`). I'm going to be touching `mkdir()` for the next release anyway (see #991), so I'll fit this in then.

**Comment by dpichard** [comment]
I got past this with `.rstrip('/')`, but then hit `java.io.FileNotFoundException: File /tmp/hadoop-tmp/.../sh does not exist`, which I figured was a PATH issue and worked around by setting `sh_bin` config option http://mrjob.readthedocs.org/en/latest/guides/configs-all-runners.html#option-sh_bin to have absolute path:
```
  runners:
    hadoop:
      sh_bin: /bin/sh -ex
```

Note sure if I'm otherwise doing something wrong myself, or MapR messed something up in v4.1, or it's a Hadoop 2 / YARN change.  Any thoughts?

**Comment by davidmarin** [comment]
Shoot, I think that's a MapR thing. At the moment, I'm at a loss for a non-invasive way to patch around that. Glad you found a workaround.

**Comment by dpichard** [comment]
Thanks for the quick response, I'll stick with the workaround, we might have something goofed up in our environment.  Thankfully I'll be able to fix for all users with `/etc/mrjob.conf`.

**Comment by davidmarin** [comment]
Okay, sounds like the trailing slash is not the reason. Closing this bug.
