### ISSUE TITLE
pip install fails on Python3

### ISSUE THREAD

**Issue by zachradtka** [Yelp/mrjob#1124]
My python version is: Python 3.4.3

When I run ```pip install mrjob``` I get the following error: 

```
> pip install mrjob
Collecting mrjob
  Using cached mrjob-0.4.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/7l/_g2hbyf54454fq4vt1h_1jgr0000gn/T/pip-build-1n04s09_/mrjob/setup.py", line 18, in <module>
        execfile(join(dirname(__file__), 'mrjob/__init__.py'))
    NameError: name 'execfile' is not defined
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/7l/_g2hbyf54454fq4vt1h_1jgr0000gn/T/pip-build-1n04s09_/mrjob
```

Is Python 3 supported?

**Comment by davidmarin** [comment]
Only in v0.5.0, which is still in development. Try the version in `master` on GitHub; it definitely works with Python 3.

**Comment by EJKwak** [comment]
Same issue here. Tried on master. No luck :( 
Running python 3.5

**Comment by duozmo** [comment]
I’ve successfully used 0.5.0-dev with Python 3.3. @EJKwak, maybe post your exact error. If it’s really the same as OP, then you aren’t on master.
