### ISSUE TITLE
inline runner can't handle second step with no mapper

### ISSUE THREAD

**Issue by btaseem** [Yelp/mrjob#1141]
Hi.

I just ran into a situation where using --strict-protocols for multi-step jobs, where the non-first job does not have a mapper with custom protocols will fail with the following error:

    ValueError: Can't pick a protocol for a non-script step

Repro code (apparently I cannot attach a python file):

    #!/usr/bin/env python
    # -*- coding: utf-8 -*-

    from mrjob.job import MRJob
    from mrjob.job import MRStep

    class CustomProtocol(object):

        def read(self, line):
            return None, line

    class TestMRJob(MRJob):

        INPUT_PROTOCOL = CustomProtocol

        def m1(self, _, v):
            for w in v.split():
                yield w, 1

        def c1(self, word, counts):
            yield word, sum(counts)

        def r1(self, word, counts):
            yield word, sum(counts)

        def r2(self, word, counts):
            yield None, '%s, %d' % (word, sum(counts))

        def steps(self):
            return [
                MRStep(mapper=self.m1,
                       combiner=self.c1,
                       reducer=self.r1),
                MRStep(reducer=self.r2)
            ]

    if __name__ == '__main__':
        TestMRJob.run()

To run it, enter any arbitrary text in a file called `data.txt` and then run it with the following command:

     python test_job.py -r inline data.txt  --strict-protocols

Stepping into the code, I can sort of see why this happens: the `step_map` is setup for an `MRStep` which then uses the specified INPUT_PROTOCOL to map a step to inputs. For steps that come second and do not have a mapper or combiner setup, there is no entry for 'mapper-1' in the step map and then fires off the exception.

I am not sure what the right way to fix this is, but perhaps allowing custom protocols per MRStep would help.

Full traceback:

	Traceback (most recent call last):
	  File "test_job.py", line 40, in <module>
		TestMRJob.run()
	  File "/work/bt/adtools/_install/lib/python2.7/site-packages/mrjob/job.py", line 461, in run
		mr_job.execute()
	  File "/work/bt/adtools/_install/lib/python2.7/site-packages/mrjob/job.py", line 479, in execute
		super(MRJob, self).execute()
	  File "/work/bt/adtools/_install/lib/python2.7/site-packages/mrjob/launch.py", line 153, in execute
		self.run_job()
	  File "/work/bt/adtools/_install/lib/python2.7/site-packages/mrjob/launch.py", line 216, in run_job
		runner.run()
	  File "/work/bt/adtools/_install/lib/python2.7/site-packages/mrjob/runner.py", line 470, in run
		self._run()
	  File "/work/bt/adtools/_install/lib/python2.7/site-packages/mrjob/sim.py", line 173, in _run
		self._invoke_step(step_num, 'mapper')
	  File "/work/bt/adtools/_install/lib/python2.7/site-packages/mrjob/sim.py", line 260, in _invoke_step
		working_dir, env)
	  File "/work/bt/adtools/_install/lib/python2.7/site-packages/mrjob/inline.py", line 160, in _run_step
		child_instance.execute()
	  File "/work/bt/adtools/_install/lib/python2.7/site-packages/mrjob/job.py", line 470, in execute
		self.run_mapper(self.options.step_num)
	  File "/work/bt/adtools/_install/lib/python2.7/site-packages/mrjob/job.py", line 527, in run_mapper
		read_lines, write_line = self._wrap_protocols(step_num, 'mapper')
	  File "/work/bt/adtools/_install/lib/python2.7/site-packages/mrjob/job.py", line 691, in _wrap_protocols
		read, write = self.pick_protocols(step_num, step_type)
	  File "/work/bt/adtools/_install/lib/python2.7/site-packages/mrjob/job.py", line 821, in pick_protocols
		p_read, p_write = self._pick_protocol_instances(step_num, step_type)
	  File "/work/bt/adtools/_install/lib/python2.7/site-packages/mrjob/job.py", line 782, in _pick_protocol_instances
		"Can't pick a protocol for a non-script step")
	ValueError: Can't pick a protocol for a non-script step

**Comment by davidmarin** [comment]
Yeah, that's definitely not right. Looking into this now.

**Comment by davidmarin** [comment]
It doesn't seem to matter if you use a custom protocol. The problem is with the inline runner; it shouldn't be trying to invoke the second step's mapper at all.

**Comment by davidmarin** [comment]
The way `local` mode gets around this is by running `cat`, just like the `hadoop` and `emr` runners. Which is correct, but doesn't help the `inline` runner. Basically this involves adding a (fairly simple) feature to `inline` mode.

**Comment by davidmarin** [comment]
Okay, looking at the stacktrace, `mrjob.inline._run_step()` is where it goes wrong. Basically, if `step` doesn't have a mapper, we should just copy `input_path` to `output_path`.

**Comment by davidmarin** [comment]
Huh, this bug exists in 0.4.5 too.

**Comment by davidmarin** [comment]
Thought this was broken in v0.4.5 too, but it actually works. So this doesn't go in `CHANGES.txt`, since it was a bug introduced in the middle of the branch.

**Comment by davidmarin** [comment]
Now fixed, thank you for catching this!

**Comment by btaseem** [comment]
Thanks for the quick turnaround.
