### ISSUE TITLE
Hadoop runner doesn't work out-of-the-box on EMR 3.7.0

### ISSUE THREAD

**Issue by davidmarin** [Yelp/mrjob#1188]
Here's the error I get:

```
$ python -m mrjob.examples.mr_wc .bashrc -r hadoop
no configs found; falling back on auto-configuration
no configs found; falling back on auto-configuration
creating tmp directory /tmp/mr_wc.hadoop.20151119.235637.628727
writing wrapper script to /tmp/mr_wc.hadoop.20151119.235637.628727/setup-wrapper.sh
Looking for hadoop binary in /home/hadoop/bin
Using Hadoop version 2.4.0
Copying local files into hdfs:///user/hadoop/tmp/mrjob/mr_wc.hadoop.20151119.235637.628727/files/
Looking for Hadoop streaming jar in /home/hadoop
Found Hadoop streaming jar: /home/hadoop/contrib/streaming/hadoop-streaming.jar
HADOOP: packageJobJar: [] [/home/hadoop/.versions/2.4.0-amzn-4/share/hadoop/tools/lib/hadoop-streaming-2.4.0-amzn-4.jar] /tmp/streamjob8604124207026505036.jar tmpDir=null
HADOOP: Connecting to ResourceManager at /172.31.29.19:9022
HADOOP: Connecting to ResourceManager at /172.31.29.19:9022
HADOOP: MetricsConfigRecord disabledInCluster: false instanceEngineCycleSec: 60 clusterEngineCycleSec: 60 disableClusterEngine: false 
HADOOP: Created MetricsSaver j-2V3F88ND4DOYM:i-b4146270:RunJar:09973 period:60 /mnt/var/em/raw/i-b4146270_20151119_null_00000_raw.bin
HADOOP: Loaded native gpl library from the embedded binaries
HADOOP: Successfully loaded & initialized native-lzo library [hadoop-lzo rev 77cfa96225d62546008ca339b7c2076a3da91578]
HADOOP: Cleaning up the staging area /tmp/hadoop-yarn/staging/hadoop/.staging/job_1447976643491_0001
HADOOP: Error Launching job : Input path does not exist: hdfs:/user/hadoop/tmp/mrjob/mr_wc.hadoop.20151119.235637.628727/files/.bashrc
HADOOP: Streaming Command Failed!
HADOOP: MetricsSaver j-2V3F88ND4DOYM:i-b4146270:RunJar:09973 metricFile /mnt/var/em/raw/i-b4146270_20151119_null_00000_raw.bin
HADOOP: Saved 3:5 records to /mnt/var/em/raw/i-b4146270_20151119_RunJar_09973_raw.bin
Job failed with return code 1280: ['/home/hadoop/bin/hadoop', 'jar', '/home/hadoop/contrib/streaming/hadoop-streaming.jar', '-files', 'hdfs:///user/hadoop/tmp/mrjob/mr_wc.hadoop.20151119.235637.628727/files/setup-wrapper.sh#setup-wrapper.sh,hdfs:///user/hadoop/tmp/mrjob/mr_wc.hadoop.20151119.235637.628727/files/mr_wc.py#mr_wc.py', '-archives', 'hdfs:///user/hadoop/tmp/mrjob/mr_wc.hadoop.20151119.235637.628727/files/mrjob.tar.gz#mrjob.tar.gz', '-input', 'hdfs:///user/hadoop/tmp/mrjob/mr_wc.hadoop.20151119.235637.628727/files/.bashrc', '-output', 'hdfs:///user/hadoop/tmp/mrjob/mr_wc.hadoop.20151119.235637.628727/output', '-mapper', 'sh -ex setup-wrapper.sh python mr_wc.py --step-num=0 --mapper', '-reducer', 'sh -ex setup-wrapper.sh python mr_wc.py --step-num=0 --reducer']
Scanning logs for probable cause of failure
Traceback (most recent call last):
  File "/usr/lib64/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.6/site-packages/mrjob/examples/mr_wc.py", line 47, in <module>
    MRWordCountUtility.run()
  File "/usr/local/lib/python2.6/site-packages/mrjob/job.py", line 433, in run
    mr_job.execute()
  File "/usr/local/lib/python2.6/site-packages/mrjob/job.py", line 451, in execute
    super(MRJob, self).execute()
  File "/usr/local/lib/python2.6/site-packages/mrjob/launch.py", line 160, in execute
    self.run_job()
  File "/usr/local/lib/python2.6/site-packages/mrjob/launch.py", line 225, in run_job
    runner.run()
  File "/usr/local/lib/python2.6/site-packages/mrjob/runner.py", line 468, in run
    self._run()
  File "/usr/local/lib/python2.6/site-packages/mrjob/hadoop.py", line 265, in _run
    self._run_job_in_hadoop()
  File "/usr/local/lib/python2.6/site-packages/mrjob/hadoop.py", line 382, in _run_job_in_hadoop
    raise CalledProcessError(returncode, step_args)
subprocess.CalledProcessError: Command '['/home/hadoop/bin/hadoop', 'jar', '/home/hadoop/contrib/streaming/hadoop-streaming.jar', '-files', 'hdfs:///user/hadoop/tmp/mrjob/mr_wc.hadoop.20151119.235637.628727/files/setup-wrapper.sh#setup-wrapper.sh,hdfs:///user/hadoop/tmp/mrjob/mr_wc.hadoop.20151119.235637.628727/files/mr_wc.py#mr_wc.py', '-archives', 'hdfs:///user/hadoop/tmp/mrjob/mr_wc.hadoop.20151119.235637.628727/files/mrjob.tar.gz#mrjob.tar.gz', '-input', 'hdfs:///user/hadoop/tmp/mrjob/mr_wc.hadoop.20151119.235637.628727/files/.bashrc', '-output', 'hdfs:///user/hadoop/tmp/mrjob/mr_wc.hadoop.20151119.235637.628727/output', '-mapper', 'sh -ex setup-wrapper.sh python mr_wc.py --step-num=0 --mapper', '-reducer', 'sh -ex setup-wrapper.sh python mr_wc.py --step-num=0 --reducer']' returned non-zero exit status 1280
```

(`hdfs:///user/hadoop/tmp/mrjob/mr_wc.hadoop.20151119.235637.628727/files/.bashrc` does exist.)

**Comment by davidmarin** [comment]
Ohhhh. This is because Hadoop ignores files starting with `.` and `_`. See #1200. When I ran it on a non-hidden file (`/etc/hosts`), it worked great.

Closing as invalid.
