### ISSUE TITLE
Error when the value of `--interpreter` does not exist on the local machine.

### ISSUE THREAD

**Issue by erose** [Yelp/mrjob#1215]
This issue occurs when I'm using the Python 2.7 with version 0.4.6 of mrjob. I haven't tested it with any other Python/version combination.

I'm using `mrjob` to run jobs on a Hadoop cluster. On the nodes of the cluster, the Python interpreter is at `weird/path/bin/python`, which does not exist on my local machine. I'm new to mrjob, but this seemed like a use case for the `--interpreter` parameter.

I run my job by running `python linecount.py`. When I add in the `--interpeter weird/path/bin/python` parameter, I get the following error:

    Traceback (most recent call last):
      File "/cogo/users/erose/.mrcloud/repos/golddigger/golddigger/mapreduce/linecount.py", line 28, in <module>
        LineCount.run()
      File "/cogo/users/erose/mrcloud/venv/lib/python2.7/site-packages/mrjob/job.py", line 461, in run
        mr_job.execute()
      File "/cogo/users/erose/mrcloud/venv/lib/python2.7/site-packages/mrjob/job.py", line 479, in execute
        super(MRJob, self).execute()
      File "/cogo/users/erose/mrcloud/venv/lib/python2.7/site-packages/mrjob/launch.py", line 153, in execute
        self.run_job()
      File "/cogo/users/erose/mrcloud/venv/lib/python2.7/site-packages/mrjob/launch.py", line 216, in run_job
        runner.run()
      File "/cogo/users/erose/mrcloud/venv/lib/python2.7/site-packages/mrjob/runner.py", line 470, in run
        self._run()
      File "/cogo/users/erose/mrcloud/venv/lib/python2.7/site-packages/mrjob/hadoop.py", line 237, in _run
        self._run_job_in_hadoop()
      File "/cogo/users/erose/mrcloud/venv/lib/python2.7/site-packages/mrjob/hadoop.py", line 309, in _run_job_in_hadoop
        for step_num in xrange(self._num_steps()):
      File "/cogo/users/erose/mrcloud/venv/lib/python2.7/site-packages/mrjob/runner.py", line 779, in _num_steps
        return len(self._get_steps())
      File "/cogo/users/erose/mrcloud/venv/lib/python2.7/site-packages/mrjob/runner.py", line 748, in _get_steps
        steps_proc = Popen(args, stdout=PIPE, stderr=PIPE, env=env)
      File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
        errread, errwrite)
      File "/usr/lib64/python2.7/subprocess.py", line 1308, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory

This error **does not happen** if I create a symlink at `weird/path/bin/python` on my machine that points to `/usr/bin/python`. (That's the workaround I'm using right now).

I'm confused about why the value of the path at `--interpreter` on the local machine would matter. Does `mrjob` use this interpreter to do something with the job locally? If so, is there another option I can use to specify an interpreter to use only on the cluster?

Let me know if I can provide any more info. Thanks. (And thanks for making mrjob!)

**Comment by davidmarin** [comment]
`--interpreter` exists to support running jobs written in other languages (e.g. Ruby, Bash); it's a feature that works but that I've never heard of anyone using.

Just use `--python-bin` if you want to set a different Python interpreter on the remote machine. It's rare to need to set the local Python bin (mrjob just uses whatever Python interpreter you ran it with), but you can use `--steps-python-bin` for that.

See:

    http://mrjob.readthedocs.org/en/latest/guides/configs-all-runners.html#option-python_bin

**Comment by erose** [comment]
Thanks! I'm using 4.6 and so was going off http://mrjob.readthedocs.org/en/latest/guides/configs-all-runners.html#option-python_bin, which says `python_bin` is deprecated, so I didn't spend too much time thinking about it. The 5.0 docs you link to are much clearer with "If you want to use an alternate Python command to run the job, use python_bin."
