### ISSUE TITLE
Cannot run program 'python3' Error on EMR

### ISSUE THREAD

**Issue by etiennebatise** [Yelp/mrjob#1326]
Hi all, 

I am trying to run a really simple job to put to push entries onto an _elasticsearch_ cluster. My `mrjob.conf` file is working and the job is also working fine locally. 

I have also successfully run several jobs on EMR but for this particular job, I have an _hadoop_ failure.

The stack trace is the following : 
```
configuration exception
java.io.IOException: Cannot run program "python3": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
        at org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:219)
        at org.apache.hadoop.streaming.PipeMapper.configure(PipeMapper.java:66)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:106)
        at org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:75)
        at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:133)
        at org.apache.hadoop.mapred.MapRunner.configure(MapRunner.java:42)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:106)
        at org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:75)
        at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:133)
        at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:427)
        at org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)
        at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1548)
        at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:170)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:186)
```

My job is the following one:
```python
import json, http.client, urllib
from mrjob.job import MRJob

class MYJob(MRJob):
 
    i = 0
    
    def mapper(self, _, line):
        line_parsed = json.loads(line)
        url = 'elasticseach.url'
        connection = http.client.HTTPConnection(url)
        headers = {'Content-Type': 'application/json'}
        connection.request('POST', '/index/field/' + str(self.i), line, headers)  

if __name__ == '__main__':
    MYJob.run()    
```
I only use the standard library (http.client, urllib) to POST on elasticsearch, so no bootstrapping issue. 

I have **never** had this problem running other python3 jobs like `mr_word_count.py` for instance, so I doubt this is the real issue here.

**Comment by etiennebatise** [comment]
Fixed when fixing this bug: https://groups.google.com/forum/#!topic/mrjob/4pYnFnRPmM8, although this one was weird.

**Comment by davidmarin** [comment]
Huh. Okay, closing for now. I don't totally understand why a firewall issue would keep Hadoop from finding `python3` (maybe it was never installed?), so if you have any information about that, please post it here. :)
