### ISSUE TITLE
handle local input dirs like Hadoop Streaming

### ISSUE THREAD

**Issue by davidmarin** [Yelp/mrjob#1338]
If you pass Hadoop Streaming a directory as input, it reads all non-"hidden" files (files whose names don't start with `_` or `.`) in that directory, but doesn't recurse into subdirectories (should double-check this).

It's confusing that we can't do the same thing with directories on the local filesystem. It'd be pretty easy to implement this.

(Thanks @rschroll for pointing this out!)

**Comment by davidmarin** [comment]
The current workaround is to use a glob:

`python mr_your_job.py input_dir/*`

**Comment by davidmarin** [comment]
The relevant issue about "hidden" input files is #1200.

Originally thought this behavior was part of Hadoop Streaming, but it's actually part of `FileInputFormat` (see http://stackoverflow.com/questions/19830264/which-files-ignored-as-input-by-mapper), which may or may not be used by other JARs.

**Comment by rschroll** [comment]
In some additional testing, we found that local directories work only if they're missing their trailing slash.  That is,
`local/dir`: Works
`local/dir/`: Doesn't work
`local/dir/*`: Works

**Comment by okomestudio** [comment]
I believe messages in this thread are mostly obsolete, as the implementation appears to have changed in v0.6.x. Nonetheless, I'll try using the thread instead of creating a new one.

I'm currently evaluating migration from v0.5.x to v0.6.1, and it looks like the behavior of input when supplied as a directory has changed in v0.6.x. In v0.5.x, I've been simply supplying a directory name (without slash as in `local/dir`) as input and things worked fine.

However, the generator method for input in v0.6.x has changed:

https://github.com/Yelp/mrjob/blob/master/mrjob/job.py#L663-L681

and, there, I think the method implementation has become inconsistent with the method docstring, and it now only accept stdin or files explicitly specified, as supplying a directory throws an IOError on https://github.com/Yelp/mrjob/blob/master/mrjob/job.py#L679.

Is this change intended? I'm not exactly sure why the support for directory input has been removed, and I believe the form `local/dir/*` only works because shell wildcard expansion, and I feel it is less elegant since it breaks symmetry with something like S3 input for which only prefix needs to be supplied.

**Comment by davidmarin** [comment]
Shoot, this behavior is actually intentional and goes hand-in-hand with the new improved local/inline mode. The idea being that streaming tasks are really only supposed to read from stdin. It used to be that local mode would pass file paths to your job, but now it sets up stdin and stdout properly just like Hadoop Streaming.

You're right though, you should be able to pass a directory and have local/inline mode read all the files in that directory that don't start with `.` or `_`. For now, please continue to use `local/dir/*` as a workaround.

**Comment by davidmarin** [comment]
Related (but probably a separate ticket): if you pass a local directory as input to mrjob and then try to run the job on EMR, it doesn't get shipped to EMR properly:

```
 $ python -m mrjob.examples.mr_word_freq_count -r emr input/
Using configs in /Users/davidmarin/.mrjob.conf
max_hours_idle is deprecated and will be removed in v0.7.0.
Using s3://mrjob-35cdec11663cb1cb/tmp/ as our temp dir on S3
Creating temp directory /var/folders/zv/jmtt5bxs6xl3kzt38470hcxm0000gn/T/mr_word_freq_count.davidmarin.20180911.191257.168106
writing master bootstrap script to /var/folders/zv/jmtt5bxs6xl3kzt38470hcxm0000gn/T/mr_word_freq_count.davidmarin.20180911.191257.168106/b.sh
Copying local files to s3://mrjob-35cdec11663cb1cb/tmp/mr_word_freq_count.davidmarin.20180911.191257.168106/files/...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/davidmarin/git/mrjob/mrjob/examples/mr_word_freq_count.py", line 37, in <module>
    MRWordFreqCount.run()
  File "mrjob/job.py", line 436, in run
    mr_job.execute()
  File "mrjob/job.py", line 457, in execute
    super(MRJob, self).execute()
  File "mrjob/launch.py", line 187, in execute
    self.run_job()
  File "mrjob/launch.py", line 235, in run_job
    runner.run()
  File "mrjob/runner.py", line 518, in run
    self._run()
  File "mrjob/emr.py", line 689, in _run
    self._launch()
  File "mrjob/emr.py", line 711, in _launch
    self._prepare_for_launch()
  File "mrjob/emr.py", line 707, in _prepare_for_launch
    self._upload_local_files_to_s3()
  File "mrjob/emr.py", line 816, in _upload_local_files_to_s3
    self._upload_contents(s3_uri, path)
  File "mrjob/emr.py", line 831, in _upload_contents
    multipart_threshold=part_size,
  File "/Users/davidmarin/git/venv-mrjob-clean/lib/python2.7/site-packages/boto3/s3/inject.py", line 280, in object_upload_file
    ExtraArgs=ExtraArgs, Callback=Callback, Config=Config)
  File "mrjob/retry.py", line 90, in call_and_maybe_retry
    return f(*args, **kwargs)
  File "/Users/davidmarin/git/venv-mrjob-clean/lib/python2.7/site-packages/boto3/s3/inject.py", line 131, in upload_file
    extra_args=ExtraArgs, callback=Callback)
  File "/Users/davidmarin/git/venv-mrjob-clean/lib/python2.7/site-packages/boto3/s3/transfer.py", line 279, in upload_file
    future.result()
  File "/Users/davidmarin/git/venv-mrjob-clean/lib/python2.7/site-packages/s3transfer/futures.py", line 73, in result
    return self._coordinator.result()
  File "/Users/davidmarin/git/venv-mrjob-clean/lib/python2.7/site-packages/s3transfer/futures.py", line 233, in result
    raise self._exception
IOError: [Errno 21] Is a directory: 'input/'
```
