### ISSUE TITLE
IOError: Could not check path  _logs

### ISSUE THREAD

**Issue by qianghuang84** [Yelp/mrjob#1355]
python 2.6, mrjob 0.5.3, hadoop 2.6.0

I installed mrjob, and can work on local. but when I run in hadoop cluster

[adadmin@s9 ~]$ python wordcount.py hdfs://s9:9900/tmp/wordcount/input/test_data.txt -v -r hadoop --hadoop-tmp-dir=hdfs://s9:9900/tmp/ 
Looking for configs in /home/adadmin/.mrjob.conf
Looking for configs in /etc/mrjob.conf
No configs found; falling back on auto-configuration
Active configuration:
{'bootstrap_mrjob': None,
 'check_input_paths': True,
 'cleanup': ['ALL'],
 'cleanup_on_failure': ['NONE'],
 'cmdenv': {},
 'hadoop_bin': None,
 'hadoop_extra_args': [],
 'hadoop_home': None,
 'hadoop_log_dirs': [],
 'hadoop_streaming_jar': None,
 'hadoop_tmp_dir': 'hdfs://s9:9900/tmp/',
 'hadoop_version': None,
 'interpreter': None,
 'jobconf': {},
 'label': None,
 'libjars': [],
 'local_tmp_dir': '/tmp',
 'owner': 'adadmin',
 'python_archives': [],
 'python_bin': None,
 'setup': [],
 'setup_cmds': [],
 'setup_scripts': [],
 'sh_bin': ['sh', '-ex'],
 'steps_interpreter': None,
 'steps_python_bin': None,
 'strict_protocols': True,
 'upload_archives': [],
 'upload_files': []}
Looking for hadoop binary in /home/adadmin/hadoop/hadoop/bin...
Found hadoop binary: /home/adadmin/hadoop/hadoop/bin/hadoop
> /home/adadmin/hadoop/hadoop/bin/hadoop fs -ls hdfs://s9:9900/tmp/wordcount/input/test_data.txt
STDOUT: -rw-r--r--   2 adadmin supergroup        927 2016-07-21 18:04 hdfs://s9:9900/tmp/wordcount/input/test_data.txt
STDERR: 16/07/22 19:07:53 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
STDERR: 16/07/22 19:07:54 WARN shortcircuit.DomainSocketFactory: The short-circuit local reads feature cannot be used because libhadoop cannot be loaded.
Creating temp directory /tmp/wordcount.adadmin.20160722.110753.079060
archiving /usr/lib/python2.6/site-packages/mrjob -> /tmp/wordcount.adadmin.20160722.110753.079060/mrjob.tar.gz as mrjob/
Writing wrapper script to /tmp/wordcount.adadmin.20160722.110753.079060/setup-wrapper.sh
WRAPPER: # store $PWD
WRAPPER: __mrjob_PWD=$PWD
WRAPPER: 
WRAPPER: # obtain exclusive file lock
WRAPPER: exec 9>/tmp/wrapper.lock.wordcount.adadmin.20160722.110753.079060
WRAPPER: python -c 'import fcntl; fcntl.flock(9, fcntl.LOCK_EX)'
WRAPPER: 
WRAPPER: # setup commands
WRAPPER: {
WRAPPER:   export PYTHONPATH=$__mrjob_PWD/mrjob.tar.gz:$PYTHONPATH
WRAPPER: } 0</dev/null 1>&2
WRAPPER: 
WRAPPER: # release exclusive file lock
WRAPPER: exec 9>&-
WRAPPER: 
WRAPPER: # run task from the original working directory
WRAPPER: cd $__mrjob_PWD
WRAPPER: "$@"
> /home/adadmin/hadoop/hadoop/bin/hadoop version
Using Hadoop version 2.6.0
> /home/adadmin/hadoop/hadoop/bin/hadoop fs -mkdir -p hdfs://s9:9900/tmp/wordcount.adadmin.20160722.110753.079060/files/
STDERR: 16/07/22 19:07:56 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
STDERR: 16/07/22 19:07:56 WARN shortcircuit.DomainSocketFactory: The short-circuit local reads feature cannot be used because libhadoop cannot be loaded.
Copying local files to hdfs://s9:9900/tmp/wordcount.adadmin.20160722.110753.079060/files/...
  /tmp/wordcount.adadmin.20160722.110753.079060/setup-wrapper.sh -> hdfs://s9:9900/tmp/wordcount.adadmin.20160722.110753.079060/files/setup-wrapper.sh
> /home/adadmin/hadoop/hadoop/bin/hadoop fs -put /tmp/wordcount.adadmin.20160722.110753.079060/setup-wrapper.sh hdfs://s9:9900/tmp/wordcount.adadmin.20160722.110753.079060/files/setup-wrapper.sh
STDERR: 16/07/22 19:07:57 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
STDERR: 16/07/22 19:07:58 WARN shortcircuit.DomainSocketFactory: The short-circuit local reads feature cannot be used because libhadoop cannot be loaded.
  /tmp/wordcount.adadmin.20160722.110753.079060/mrjob.tar.gz -> hdfs://s9:9900/tmp/wordcount.adadmin.20160722.110753.079060/files/mrjob.tar.gz
> /home/adadmin/hadoop/hadoop/bin/hadoop fs -put /tmp/wordcount.adadmin.20160722.110753.079060/mrjob.tar.gz hdfs://s9:9900/tmp/wordcount.adadmin.20160722.110753.079060/files/mrjob.tar.gz
STDERR: 16/07/22 19:07:59 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
STDERR: 16/07/22 19:08:00 WARN shortcircuit.DomainSocketFactory: The short-circuit local reads feature cannot be used because libhadoop cannot be loaded.
  /data/adadmin/wordcount.py -> hdfs://s9:9900/tmp/wordcount.adadmin.20160722.110753.079060/files/wordcount.py
> /home/adadmin/hadoop/hadoop/bin/hadoop fs -put /data/adadmin/wordcount.py hdfs://s9:9900/tmp/wordcount.adadmin.20160722.110753.079060/files/wordcount.py
STDERR: 16/07/22 19:08:01 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
STDERR: 16/07/22 19:08:01 WARN shortcircuit.DomainSocketFactory: The short-circuit local reads feature cannot be used because libhadoop cannot be loaded.
> /usr/bin/python /data/adadmin/wordcount.py --steps
Looking for Hadoop streaming jar in /home/adadmin/hadoop/hadoop...
Found Hadoop streaming jar: /home/adadmin/hadoop/hadoop/share/hadoop/tools/lib/hadoop-streaming-2.6.0-cdh5.5.1.jar
Running step 1 of 1...
> /home/adadmin/hadoop/hadoop/bin/hadoop jar /home/adadmin/hadoop/hadoop/share/hadoop/tools/lib/hadoop-streaming-2.6.0-cdh5.5.1.jar -files 'hdfs://s9:9900/tmp/wordcount.adadmin.20160722.110753.079060/files/wordcount.py#wordcount.py,hdfs://s9:9900/tmp/wordcount.adadmin.20160722.110753.079060/files/setup-wrapper.sh#setup-wrapper.sh' -archives 'hdfs://s9:9900/tmp/wordcount.adadmin.20160722.110753.079060/files/mrjob.tar.gz#mrjob.tar.gz' -input hdfs://s9:9900/tmp/wordcount/input/test_data.txt -output hdfs://s9:9900/tmp/wordcount.adadmin.20160722.110753.079060/output -mapper 'sh -ex setup-wrapper.sh python wordcount.py --step-num=0 --mapper' -combiner 'sh -ex setup-wrapper.sh python wordcount.py --step-num=0 --combiner' -reducer 'sh -ex setup-wrapper.sh python wordcount.py --step-num=0 --reducer'
Invoking Hadoop via PTY
  Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
  The short-circuit local reads feature cannot be used because libhadoop cannot be loaded.
  packageJobJar: [/tmp/hadoop-unjar3823634434464941169/] [] /tmp/streamjob8659778638895793056.jar tmpDir=null
  Connecting to ResourceManager at s9/10.121.93.49:8032
  Connecting to ResourceManager at s9/10.121.93.49:8032
  Total input paths to process : 1
  number of splits:2
  Submitting tokens for job: job_1468898795401_0059
  Submitted application application_1468898795401_0059
  The url to track the job: http://s9:8088/proxy/application_1468898795401_0059/
  Running job: job_1468898795401_0059
  Job job_1468898795401_0059 running in uber mode : false
   map 0% reduce 0%
  Task Id : attempt_1468898795401_0059_m_000000_0, Status : FAILED
Error: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 2
	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:325)
	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:538)
	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:453)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:163)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1671)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)

  Task Id : attempt_1468898795401_0059_m_000001_0, Status : FAILED
Error: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 2
	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:325)
	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:538)
	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:453)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:163)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1671)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)

  Task Id : attempt_1468898795401_0059_m_000000_1, Status : FAILED
Error: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 2
	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:325)
	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:538)
	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:453)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:163)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1671)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)

  Task Id : attempt_1468898795401_0059_m_000001_1, Status : FAILED
Error: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 2
	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:325)
	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:538)
	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:453)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:163)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1671)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)

  Task Id : attempt_1468898795401_0059_m_000000_2, Status : FAILED
Error: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 2
	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:325)
	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:538)
	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:453)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:163)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1671)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)

   map 100% reduce 100%
  Job job_1468898795401_0059 failed with state FAILED due to: Task failed task_1468898795401_0059_m_000000
Job failed as tasks failed. failedMaps:1 failedReduces:0

  Job not successful!
  Streaming Command Failed!
Counters: 14
	Job Counters 
		Data-local map tasks=1
		Failed map tasks=6
		Killed map tasks=1
		Launched map tasks=7
		Other local map tasks=5
		Rack-local map tasks=1
		Total megabyte-seconds taken by all map tasks=37486592
		Total time spent by all map tasks (ms)=36608
		Total time spent by all maps in occupied slots (ms)=36608
		Total time spent by all reduces in occupied slots (ms)=0
		Total vcore-seconds taken by all map tasks=36608
	Map-Reduce Framework
		CPU time spent (ms)=0
		Physical memory (bytes) snapshot=0
		Virtual memory (bytes) snapshot=0
Scanning logs for probable cause of failure...
> /home/adadmin/hadoop/hadoop/bin/hadoop fs -ls hdfs:///tmp/hadoop-yarn/staging
STDOUT: Found 3 items
STDOUT: drwx------   - adadmin supergroup          0 2015-12-24 11:37 hdfs:///tmp/hadoop-yarn/staging/adadmin
STDOUT: drwxr-xr-x   - hue     supergroup          0 2015-12-24 11:20 hdfs:///tmp/hadoop-yarn/staging/history
STDOUT: drwx------   - hue     supergroup          0 2015-12-24 11:17 hdfs:///tmp/hadoop-yarn/staging/hue
STDERR: 16/07/22 19:09:06 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
STDERR: 16/07/22 19:09:07 WARN shortcircuit.DomainSocketFactory: The short-circuit local reads feature cannot be used because libhadoop cannot be loaded.
Looking for history log in hdfs:///tmp/hadoop-yarn/staging...
> /home/adadmin/hadoop/hadoop/bin/hadoop fs -ls hdfs:///tmp/hadoop-yarn/staging
STDOUT: Found 3 items
STDOUT: drwx------   - adadmin supergroup          0 2015-12-24 11:37 hdfs:///tmp/hadoop-yarn/staging/adadmin
STDOUT: drwxr-xr-x   - hue     supergroup          0 2015-12-24 11:20 hdfs:///tmp/hadoop-yarn/staging/history
STDOUT: drwx------   - hue     supergroup          0 2015-12-24 11:17 hdfs:///tmp/hadoop-yarn/staging/hue
STDERR: 16/07/22 19:09:08 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
STDERR: 16/07/22 19:09:08 WARN shortcircuit.DomainSocketFactory: The short-circuit local reads feature cannot be used because libhadoop cannot be loaded.
> /home/adadmin/hadoop/hadoop/bin/hadoop fs -ls -R hdfs:///tmp/hadoop-yarn/staging
STDERR: 16/07/22 19:09:09 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
STDERR: 16/07/22 19:09:10 WARN shortcircuit.DomainSocketFactory: The short-circuit local reads feature cannot be used because libhadoop cannot be loaded.
> /home/adadmin/hadoop/hadoop/bin/hadoop fs -ls hdfs://s9:9900/tmp/wordcount.adadmin.20160722.110753.079060/output/_logs
STDERR: 16/07/22 19:09:11 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
STDERR: 16/07/22 19:09:12 WARN shortcircuit.DomainSocketFactory: The short-circuit local reads feature cannot be used because libhadoop cannot be loaded.
STDERR: ls: `hdfs://s9:9900/tmp/wordcount.adadmin.20160722.110753.079060/output/_logs': No such file or directory
Traceback (most recent call last):
  File "wordcount.py", line 21, in <module>
    MRWordFreqCount.run()
  File "/usr/lib/python2.6/site-packages/mrjob/job.py", line 433, in run
    mr_job.execute()
  File "/usr/lib/python2.6/site-packages/mrjob/job.py", line 451, in execute
    super(MRJob, self).execute()
  File "/usr/lib/python2.6/site-packages/mrjob/launch.py", line 160, in execute
    self.run_job()
  File "/usr/lib/python2.6/site-packages/mrjob/launch.py", line 230, in run_job
    runner.run()
  File "/usr/lib/python2.6/site-packages/mrjob/runner.py", line 474, in run
    self._run()
  File "/usr/lib/python2.6/site-packages/mrjob/hadoop.py", line 335, in _run
    self._run_job_in_hadoop()
  File "/usr/lib/python2.6/site-packages/mrjob/hadoop.py", line 451, in _run_job_in_hadoop
    error = self._pick_error(log_interpretation)
  File "/usr/lib/python2.6/site-packages/mrjob/logs/mixin.py", line 114, in _pick_error
    self._interpret_history_log(log_interpretation)
  File "/usr/lib/python2.6/site-packages/mrjob/logs/mixin.py", line 138, in _interpret_history_log
    job_id=job_id, output_dir=output_dir))
  File "/usr/lib/python2.6/site-packages/mrjob/logs/history.py", line 122, in _interpret_history_log
    for match in matches:
  File "/usr/lib/python2.6/site-packages/mrjob/logs/mixin.py", line 145, in _ls_history_logs
    job_id=job_id):
  File "/usr/lib/python2.6/site-packages/mrjob/logs/history.py", line 91, in _ls_history_logs
    job_id=job_id)
  File "/usr/lib/python2.6/site-packages/mrjob/logs/wrap.py", line 66, in _ls_logs
    for log_dirs in log_dir_stream:
  File "/usr/lib/python2.6/site-packages/mrjob/hadoop.py", line 590, in _stream_history_log_dirs
    if self.fs.exists(log_dir):
  File "/usr/lib/python2.6/site-packages/mrjob/fs/composite.py", line 79, in exists
    return self._do_action('exists', path_glob)
  File "/usr/lib/python2.6/site-packages/mrjob/fs/composite.py", line 63, in _do_action
    raise first_exception
IOError: Could not check path hdfs://s9:9900/tmp/wordcount.adadmin.20160722.110753.079060/output/_logs

I'm still can't find the bug,  anyone can help me. thanks in advanced.

**Comment by davidmarin** [comment]
Oops, log parsing code is supposed to ignore IOError and move on. Thanks for catching this.

**Comment by qianghuang84** [comment]
according to your information. what steps need to be done to make the program running?

**Comment by davidmarin** [comment]
Okay, this is in `master` and will go into v0.5.4.
