### ISSUE TITLE
Log4j returns warnings when running on EMR

### ISSUE THREAD

**Issue by etiennebatise** [Yelp/mrjob#1359]
python3 - mrjob 0.5.2
When running a job on EMR, I got the following warnings in the stderr files of each container:
```
log4j:WARN No appenders could be found for logger (org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```

**Comment by etiennebatise** [comment]
A bit of context, I've noticed those warnings when encountering the following error (maybe this is somehow linked): 
```
log4j:ERROR Failed to flush writer,
java.io.IOException: No space left on device
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:345)
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
	at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
	at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
	at org.apache.log4j.helpers.QuietWriter.flush(QuietWriter.java:59)
	at org.apache.log4j.WriterAppender.subAppend(WriterAppender.java:324)
	at org.apache.log4j.WriterAppender.append(WriterAppender.java:162)
	at org.apache.hadoop.yarn.ContainerLogAppender.append(ContainerLogAppender.java:61)
	at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
	at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
	at org.apache.log4j.Category.callAppenders(Category.java:206)
	at org.apache.log4j.Category.forcedLog(Category.java:391)
	at org.apache.log4j.Category.log(Category.java:856)
	at org.slf4j.impl.Log4jLoggerAdapter.error(Log4jLoggerAdapter.java:540)
	at amazon.emr.metrics.MetricsSaver.flush(MetricsSaver.java:538)
	at amazon.emr.metrics.MetricsSaver.run(MetricsSaver.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
log4j:WARN No appenders could be found for logger (org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```

**Comment by davidmarin** [comment]
Yeah, it sounds like you've run out of space on that node for some reason. The log4j warnings aren't really that important; perhaps setting up logging happens after making that directory, or there wasn't space for the log4j.properties file?

**Comment by etiennebatise** [comment]
Yes, this is an easy error (just added some instances) but I find it unfortunate that the job fails because logging fails, losing all the output and everything.
