### ISSUE TITLE
Spark error log parsing

### ISSUE THREAD

**Issue by davidmarin** [Yelp/mrjob#1378]
We should parse probably cause of error from Spark error logs.

At least on EMR, it seems like Spark works similarly to Hadoop Streaming, but that it spits stuff into different logs.

For starters, the stuff we get from `steps/s-XXXXX/syslog` for streaming jobs appears in `steps/s-XXXXX/stderr` for Spark jobs. This pretty much just gives us application ID and a fallback error, but that's useful. Spark doesn't create counters, so we shouldn't ask for them.

And then the task logs appear in `hadoop-yarn/containers/application_*/container_*/`, like with streaming steps, but the output of the step is in `stdout` (!), and the stuff that's usually in `syslog` is in `stderr` (there is no `syslog` file).

(Possibly EMR's Spark stuff is just misconfigured?)

Also, on later 4.x AMIs the application logs are owned by `yarn` and not available to the `hadoop` user, so we really need to enable `sudo` for log fetching (#1244).

We can punt on the history logs; they're only available inside HDFS on the 4.x AMIs, and they don't provide any additional value over the step and task logs anyways.

**Comment by davidmarin** [comment]
Currently when there's an error with a Spark step on EMR, mrjob uses the code which is designed to catch errors from `script-runner.jar`. This prints the entire output of `spark-submit`, which is... not unhelpful. And of course it makes a futile search for counters.

**Comment by davidmarin** [comment]
Should be pretty straightforward to test this on Hadoop; just need to use one of the AMIs that doesn't have permissions problems with the application logs.

**Comment by davidmarin** [comment]
Looks like the step logs are different too, at least on EMR. Basically, because EMR runs Spark in cluster mode, there are two logs, `controller.gz` (which is the output of the `spark-submit` command, I think?) and and `stderr.gz` (which is the log for the Spark client launched in the cluster).

Pretty sure we want to prioritize `stderr` over `controller` (because it's closer to the proximate cause of the error).

**Comment by davidmarin** [comment]
`task_attempts/container_*/application_*/stdout` (which is Spark's equivalent of the `stderr` log) includes a lot of GC crud like this:

```
2016-11-15T23:58:22.850+0000: [GC[YG occupancy: 81665 K (153344 K)]2016-11-15T23:58:22.850+0000: [Rescan (parallel) , 0.0243740 secs]2016-11-15T23:58:22.874+0000: [weak refs processing, 0.0000470 secs]2016-11-15T23:58:22.874+0000: [class unloading, 0.0060330 secs]2016-11-15T23:58:22.880+0000: [scrub symbol table, 0.0075500 secs]2016-11-15T23:58:22.888+0000: [scrub string table, 0.0034400 secs] [1 CMS-remark: 855K(878208K)] 82521K(1031552K), 0.0421760 secs] [Times: user=0.05 sys=0.00, real=0.04 secs] 
```

**Comment by davidmarin** [comment]
Also, the syslog (`stderr` for Spark) is pretty noisy. Here's a Java exception from a successful job, indicating that a worker was no longer needed:

```
16/11/15 23:58:41 WARN channel.DefaultChannelPipeline: An exception was thrown by an exception handler.
java.util.concurrent.RejectedExecutionException: Worker has already been shutdown
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.registerTask(AbstractNioSelector.java:120)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.executeInIoThread(AbstractNioWorker.java:72)
	at org.jboss.netty.channel.socket.nio.NioWorker.executeInIoThread(NioWorker.java:36)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.executeInIoThread(AbstractNioWorker.java:56)
	at org.jboss.netty.channel.socket.nio.NioWorker.executeInIoThread(NioWorker.java:36)
	at org.jboss.netty.channel.socket.nio.AbstractNioChannelSink.execute(AbstractNioChannelSink.java:34)
	at org.jboss.netty.channel.Channels.fireExceptionCaughtLater(Channels.java:496)
	at org.jboss.netty.channel.AbstractChannelSink.exceptionCaught(AbstractChannelSink.java:46)
	at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:54)
	at org.jboss.netty.channel.Channels.disconnect(Channels.java:781)
	at org.jboss.netty.channel.AbstractChannel.disconnect(AbstractChannel.java:211)
	at akka.remote.transport.netty.NettyTransport$$anonfun$gracefulClose$1.apply(NettyTransport.scala:223)
	at akka.remote.transport.netty.NettyTransport$$anonfun$gracefulClose$1.apply(NettyTransport.scala:222)
	at scala.util.Success.foreach(Try.scala:205)
	at scala.concurrent.Future$$anonfun$foreach$1.apply(Future.scala:204)
	at scala.concurrent.Future$$anonfun$foreach$1.apply(Future.scala:204)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by davidmarin** [comment]
Really shouldn't be developing Spark error log parsing on 3.x AMIs. Seems like the job can just silently fail and EMR will report it as complete.

Some of this is just the very old version of Spark on the 3.x AMIs. For example, on AMI version 3.11.0, `spark-submit` will treat a job like this as successful:

```
    def spark(self, input_path, output_path):
        # Spark may not be available where script is launched
        from pyspark import SparkContext

        sc = SparkContext(appName='mrjob Spark wordcount script')

        lines = sc.textFile(input_path)

        def kaboom(line):
            raise Exception('KABOOM')

        # make sure the exception happens inside Spark, not just at the
        # top-level client
        kaboomed_lines = lines.flatMap(kaboom)
        kaboomed_lines.saveAsTextFile(output_path)

        sc.stop()
```

Whereas on 4.7.2, this is definitely a failure, both from the point of view of `spark-submit` and EMR.

**Comment by davidmarin** [comment]
Well, shoot, it's not as simple as the task logs having different names.

If there's an exception somewhere inside Spark (like you would with the script above), the exception is included inside in the Java stack trace in `stderr`:

```
16/11/16 22:05:00 ERROR Executor: Exception in task 0.2 in stage 0.0 (TID 4)
org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/mnt/yarn/usercache/hadoop/appcache/application_1479325434015_0003/conta
iner_1479325434015_0003_02_000002/pyspark.zip/pyspark/worker.py", line 111, in main
    process()
  File "/mnt/yarn/usercache/hadoop/appcache/application_1479325434015_0003/container_1479325434015_0003_02_000002/pyspark.zip/pyspark/worker.py", line 106, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/mnt/yarn/usercache/hadoop/appcache/application_1479325434015_0003/container_1479325434015_0003_02_000002/pyspark.zip/pyspark/serializers.py", line 133, in dump_stream
    for obj in iterator:
  File "/mnt/yarn/usercache/hadoop/appcache/application_1479325434015_0003/container_1479325434015_0003_02_000001/pyspark.zip/pyspark/rdd.py", line 1494, in func
  File "mr_sparkaboom.py", line 28, in kaboom
Exception: KABOOM

        at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRDD.scala:166)
        at org.apache.spark.api.python.PythonRunner$$anon$1.<init>(PythonRDD.scala:207)
        at org.apache.spark.api.python.PythonRunner.compute(PythonRDD.scala:125)
        at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:70)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
        at org.apache.spark.scheduler.Task.run(Task.scala:89)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:227)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

The `stdout` file is useless here; it just contains GC logging crud.

**Comment by davidmarin** [comment]
If you raise an exception before initializing a `SparkContext`, the `stdout` file contains the Python stacktrace and nothing else, and the `stderr` file contains something like this:

```
16/11/16 22:26:22 ERROR ApplicationMaster: User application exited with status 1
16/11/16 22:26:22 INFO ApplicationMaster: Final app status: FAILED, exitCode: 1, (reason: User application exited with status 1)
16/11/16 22:26:31 ERROR ApplicationMaster: SparkContext did not initialize after waiting for 100000 ms. Please check earlier log output for errors. Failing the application.
```

**Comment by davidmarin** [comment]
If the exception happens after `SparkContext` is initialized, but in the main script (not inside the processing of the RDD), you get basically the same thing:

```
16/11/16 23:20:03 ERROR ApplicationMaster: User application exited with status 1
```

Of course, there's no error about `SparkContext` not being initialized.

**Comment by davidmarin** [comment]
Fundamentally, we need a different process for parsing task logs than we use for streaming tasks.

For streaming, it's all about finding the most interesting error, which means the one with the Python traceback.

For Spark, really the most recent error is fine. But we want to know when to inspect `stdout` and when it's not important.

**Comment by davidmarin** [comment]
The `controller` step log on EMR doesn't appear to contain errors or anything else we need; fine to just focus on the `stderr` log.

**Comment by davidmarin** [comment]
Also, the two kinds of Spark task errors happen in different containers. The one that logs `ApplicationMaster` errors (and requires us to check `stdout`) is in one of the "earlier" containers, so we'll naturally prioritize exceptions inside Spark's RDD processing.
