### ISSUE TITLE
ignore subprocess failed in task stderr (Hadoop 1)

### ISSUE THREAD

**Issue by davidmarin** [Yelp/mrjob#1430]
The most useful thing we can show a user whose streaming job failed is stderr from a task. Unfortunately, on Hadoop 1 the `stderr` task log file also generally contains a "subprocess failed" Java stacktrace. We should strip that the same way we currently strip log4j initialization warnings.

**Comment by davidmarin** [comment]
An example (on mrjob 0.5.5):

```
$ python -m mrjob.examples.mr_boom -r emr --image-version 3.11.0 mrjob/LICENSE.txt
Using configs in /Users/davidmarin/.mrjob.conf
Using s3://mrjob-35cdec11663cb1cb/tmp/ as our temp dir on S3
Creating temp directory /var/folders/zv/jmtt5bxs6xl3kzt38470hcxm0000gn/T/mr_boom.davidmarin.20160909.203206.638356
Copying local files to s3://mrjob-35cdec11663cb1cb/tmp/mr_boom.davidmarin.20160909.203206.638356/files/...
Attempting to find an available cluster...
Created new cluster j-2NYO3SH3721L5
Waiting for step 1 of 1 (s-2GUPOC1R4M34I) to complete...
  PENDING (cluster is STARTING)
  PENDING (cluster is STARTING)
  PENDING (cluster is STARTING)
  PENDING (cluster is STARTING)
  PENDING (cluster is STARTING)
  PENDING (cluster is STARTING)
  PENDING (cluster is STARTING)
  PENDING (cluster is STARTING)
  PENDING (cluster is BOOTSTRAPPING: Running bootstrap actions)
  PENDING (cluster is BOOTSTRAPPING: Running bootstrap actions)
  PENDING (cluster is BOOTSTRAPPING: Running bootstrap actions)
  PENDING (cluster is BOOTSTRAPPING: Running bootstrap actions)
  PENDING (cluster is BOOTSTRAPPING: Running bootstrap actions)
  PENDING (cluster is BOOTSTRAPPING: Running bootstrap actions)
  Opening ssh tunnel to resource manager...
  Connect to resource manager at: http://localhost:40106/cluster
  RUNNING for 11.6s
  RUNNING for 45.6s
     0.0% complete
  RUNNING for 77.6s
     5.0% complete
  RUNNING for 108.1s
     5.0% complete
  RUNNING for 138.8s
   100.0% complete
  FAILED
Cluster j-2NYO3SH3721L5 is WAITING: Cluster ready after last step failed.
Attempting to fetch counters from logs...
Looking for step log in /mnt/var/log/hadoop/steps/s-2GUPOC1R4M34I on ec2-54-68-88-123.us-west-2.compute.amazonaws.com...
  Parsing step log: ssh://ec2-54-68-88-123.us-west-2.compute.amazonaws.com/mnt/var/log/hadoop/steps/s-2GUPOC1R4M34I/syslog
Counters: 9
	Job Counters 
		Data-local map tasks=1
		Failed map tasks=4
		Launched map tasks=4
		Other local map tasks=3
		Total megabyte-seconds taken by all map tasks=55522560
		Total time spent by all map tasks (ms)=72295
		Total time spent by all maps in occupied slots (ms)=216885
		Total time spent by all reduces in occupied slots (ms)=0
		Total vcore-seconds taken by all map tasks=72295
Scanning logs for probable cause of failure...
Looking for task logs in /mnt/var/log/hadoop/userlogs/application_1473453507163_0001 on ec2-54-68-88-123.us-west-2.compute.amazonaws.com and task/core nodes...
  Parsing task syslog: ssh://ec2-54-68-88-123.us-west-2.compute.amazonaws.com/mnt/var/log/hadoop/userlogs/application_1473453507163_0001/container_1473453507163_0001_01_000005/syslog
  Parsing task stderr: ssh://ec2-54-68-88-123.us-west-2.compute.amazonaws.com/mnt/var/log/hadoop/userlogs/application_1473453507163_0001/container_1473453507163_0001_01_000005/stderr
Probable cause of failure:

PipeMapRed failed!
java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 1
	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:330)
	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:543)
	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:81)
	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:432)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1548)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:170)

(from lines 36-49 of ssh://ec2-54-68-88-123.us-west-2.compute.amazonaws.com/mnt/var/log/hadoop/userlogs/application_1473453507163_0001/container_1473453507163_0001_01_000005/syslog)

caused by:

Traceback (most recent call last):
  File "mr_boom.py", line 10, in <module>
    MRBoom.run()
  File "/usr/lib/python2.7/dist-packages/mrjob/job.py", line 429, in run
    mr_job.execute()
  File "/usr/lib/python2.7/dist-packages/mrjob/job.py", line 438, in execute
    self.run_mapper(self.options.step_num)
  File "/usr/lib/python2.7/dist-packages/mrjob/job.py", line 499, in run_mapper
    for out_key, out_value in mapper_init() or ():
  File "mr_boom.py", line 7, in mapper_init
    raise Exception('BOOM')
Exception: BOOM

(from lines 1-12 of ssh://ec2-54-68-88-123.us-west-2.compute.amazonaws.com/mnt/var/log/hadoop/userlogs/application_1473453507163_0001/container_1473453507163_0001_01_000005/stderr)

while reading input from s3://mrjob-35cdec11663cb1cb/tmp/mr_boom.davidmarin.20160909.203206.638356/files/LICENSE.txt


Step 1 of 1 failed
Killing our SSH tunnel (pid 27963)
```

**Comment by davidmarin** [comment]
An example (running mrjob 0.5.5):

```
$ python -m mrjob.examples.mr_boom -r emr --image-version 2.4.9 mrjob/LICENSE.txt 
Using configs in /Users/davidmarin/.mrjob.conf
Using s3://mrjob-35cdec11663cb1cb/tmp/ as our temp dir on S3
Creating temp directory /var/folders/zv/jmtt5bxs6xl3kzt38470hcxm0000gn/T/mr_boom.davidmarin.20160909.202932.798215
Copying local files to s3://mrjob-35cdec11663cb1cb/tmp/mr_boom.davidmarin.20160909.202932.798215/files/...
Attempting to find an available cluster...
Created new cluster j-FIOO0N86BX4L
Waiting for step 1 of 1 (s-WGXCKHCWKQ1I) to complete...
  PENDING (cluster is STARTING)
  PENDING (cluster is STARTING)
  PENDING (cluster is STARTING)
  PENDING (cluster is STARTING)
  PENDING (cluster is STARTING: Configuring cluster software)
  PENDING (cluster is BOOTSTRAPPING: Running bootstrap actions)
  PENDING (cluster is BOOTSTRAPPING: Running bootstrap actions)
  Opening ssh tunnel to job tracker...
  Connect to job tracker at: http://localhost:40441/jobtracker.jsp
  RUNNING for 3.9s
  RUNNING for 36.5s
   map   0% reduce   0%
  RUNNING for 67.0s
   map   0% reduce   0%
  RUNNING for 97.8s
   map   0% reduce   0%
  FAILED
Cluster j-FIOO0N86BX4L is WAITING: Cluster ready after last step failed.
Attempting to fetch counters from logs...
Looking for step log in /mnt/var/log/hadoop/steps/s-WGXCKHCWKQ1I on ec2-52-43-129-16.us-west-2.compute.amazonaws.com...
  Parsing step log: ssh://ec2-52-43-129-16.us-west-2.compute.amazonaws.com/mnt/var/log/hadoop/steps/s-WGXCKHCWKQ1I/syslog
Looking for history log in /mnt/var/log/hadoop/history on ec2-52-43-129-16.us-west-2.compute.amazonaws.com...
  Parsing history log: ssh://ec2-52-43-129-16.us-west-2.compute.amazonaws.com/mnt/var/log/hadoop/history/done/version-1/ip-172-31-40-22.us-west-2.compute.internal_1473453174978_/2016/09/09/000000/job_201609092032_0001_1473453246675_hadoop_streamjob8768385455319550250.jar
Counters: 6
	FileSystemCounters
		FILE_BYTES_WRITTEN=52616
	Map-Reduce Framework
		CPU time spent (ms)=290
		Physical memory (bytes) snapshot=207302656
		Spilled Records=0
		Total committed heap usage (bytes)=119013376
		Virtual memory (bytes) snapshot=1854636032
Scanning logs for probable cause of failure...
Looking for task logs in /mnt/var/log/hadoop/userlogs on ec2-52-43-129-16.us-west-2.compute.amazonaws.com and task/core nodes...
  Parsing task syslog: ssh://ec2-52-43-129-16.us-west-2.compute.amazonaws.com/mnt/var/log/hadoop/userlogs/job_201609092032_0001/attempt_201609092032_0001_m_000001_3/syslog
  Parsing task stderr: ssh://ec2-52-43-129-16.us-west-2.compute.amazonaws.com/mnt/var/log/hadoop/userlogs/job_201609092032_0001/attempt_201609092032_0001_m_000001_3/stderr
Probable cause of failure:

Error running child
java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 1
	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:372)
	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:586)
	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:136)
	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:63)
	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:36)
	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:441)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:377)
	at org.apache.hadoop.mapred.Child$4.run(Child.java:259)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1140)
	at org.apache.hadoop.mapred.Child.main(Child.java:253)

(from lines 28-41 of ssh://ec2-52-43-129-16.us-west-2.compute.amazonaws.com/mnt/var/log/hadoop/userlogs/job_201609092032_0001/attempt_201609092032_0001_m_000001_3/syslog)

caused by:

Traceback (most recent call last):
  File "mr_boom.py", line 10, in <module>
    MRBoom.run()
  File "/usr/lib/python2.7/site-packages/mrjob/job.py", line 429, in run
    mr_job.execute()
  File "/usr/lib/python2.7/site-packages/mrjob/job.py", line 438, in execute
    self.run_mapper(self.options.step_num)
  File "/usr/lib/python2.7/site-packages/mrjob/job.py", line 499, in run_mapper
    for out_key, out_value in mapper_init() or ():
  File "mr_boom.py", line 7, in mapper_init
    raise Exception('BOOM')
Exception: BOOM
java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 1
	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:372)
	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:586)
	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:136)
	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:63)
	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:36)
	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:441)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:377)
	at org.apache.hadoop.mapred.Child$4.run(Child.java:259)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1140)
	at org.apache.hadoop.mapred.Child.main(Child.java:253)

(from lines 1-25 of ssh://ec2-52-43-129-16.us-west-2.compute.amazonaws.com/mnt/var/log/hadoop/userlogs/job_201609092032_0001/attempt_201609092032_0001_m_000001_3/stderr)

while reading input from s3://mrjob-35cdec11663cb1cb/tmp/mr_boom.davidmarin.20160909.202932.798215/files/LICENSE.txt


Step 1 of 1 failed
Killing our SSH tunnel (pid 27877)
```
