### ISSUE TITLE
bump google-api-python-client version?

### ISSUE THREAD

**Issue by davidmarin** [Yelp/mrjob#1434]
My old version of `google-api-python-client` (probably 1.5.0) gave some unhelpful errors when trying to run a basic job:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/davidmarin/git/mrjob/mrjob/examples/mr_word_freq_count.py", line 37, in <module>
    MRWordFreqCount.run()
  File "mrjob/job.py", line 429, in run
    mr_job.execute()
  File "mrjob/job.py", line 447, in execute
    super(MRJob, self).execute()
  File "mrjob/launch.py", line 158, in execute
    self.run_job()
  File "mrjob/launch.py", line 226, in run_job
    with self.make_runner() as runner:
  File "mrjob/job.py", line 471, in make_runner
    return super(MRJob, self).make_runner()
  File "mrjob/launch.py", line 173, in make_runner
    return DataprocJobRunner(**self.dataproc_job_runner_kwargs())
  File "mrjob/dataproc.py", line 324, in __init__
    base_tmpdir = self._get_tmpdir(self._opts['cloud_tmp_dir'])
  File "mrjob/dataproc.py", line 406, in _get_tmpdir
    self._gcp_project, prefix='mrjob-')
  File "mrjob/fs/gcs.py", line 282, in list_buckets
    req = self.api_client.buckets().list(**list_kwargs)
  File "mrjob/fs/gcs.py", line 90, in api_client
    credentials = GoogleCredentials.get_application_default()
AttributeError: 'NoneType' object has no attribute 'get_application_default'
```

Upgrading to 1.5.3 gave me a more helpful error:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/davidmarin/git/mrjob/mrjob/examples/mr_word_freq_count.py", line 37, in <module>
    MRWordFreqCount.run()
  File "mrjob/job.py", line 429, in run
    mr_job.execute()
  File "mrjob/job.py", line 447, in execute
    super(MRJob, self).execute()
  File "mrjob/launch.py", line 158, in execute
    self.run_job()
  File "mrjob/launch.py", line 228, in run_job
    runner.run()
  File "mrjob/runner.py", line 481, in run
    self._run()
  File "mrjob/dataproc.py", line 434, in _run
    self._launch()
  File "mrjob/dataproc.py", line 438, in _launch
    self._prepare_for_launch()
  File "mrjob/dataproc.py", line 447, in _prepare_for_launch
    self._upload_local_files_to_fs()
  File "mrjob/dataproc.py", line 520, in _upload_local_files_to_fs
    self._create_fs_tmp_bucket(bucket_name)
  File "mrjob/dataproc.py", line 555, in _create_fs_tmp_bucket
    object_ttl_days=_DEFAULT_CLOUD_TMP_DIR_OBJECT_TTL_DAYS)
  File "mrjob/fs/gcs.py", line 310, in create_bucket
    return req.execute()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/googleapiclient/http.py", line 838, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/storage/v1/b?project=mrjob-testing&alt=json returned "The account for the specified project has been disabled.">
```

It _might_ be that both versions work fine for a non-disabled account; will take a look.

**Comment by davidmarin** [comment]
No longer relevant since we ported to `google-cloud`. See #1741.
