### ISSUE TITLE
dataproc: auto-create default network

### ISSUE THREAD

**Issue by davidmarin** [Yelp/mrjob#1436]
Got this error:

```
Traceback (most recent call last):
  File "mrjob/dataproc.py", line 604, in _cleanup_cluster
    self._api_cluster_delete(self._cluster_id)
  File "mrjob/dataproc.py", line 1096, in _api_cluster_delete
    clusterName=cluster_id
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/googleapiclient/http.py", line 838, in execute
    raise HttpError(resp, content, uri=self.uri)
HttpError: <HttpError 404 when requesting https://dataproc.googleapis.com/v1/projects/mrjob-testing/regions/global/clusters/mrjob-us-central1-a-f676cb0c483f75cd?alt=json returned "Not found: project id: 'mrjob-testing' clusterName: 'mrjob-us-central1-a-f676cb0c483f75cd'">
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/davidmarin/git/mrjob/mrjob/examples/mr_word_freq_count.py", line 37, in <module>
    MRWordFreqCount.run()
  File "mrjob/job.py", line 429, in run
    mr_job.execute()
  File "mrjob/job.py", line 447, in execute
    super(MRJob, self).execute()
  File "mrjob/launch.py", line 158, in execute
    self.run_job()
  File "mrjob/launch.py", line 228, in run_job
    runner.run()
  File "mrjob/runner.py", line 481, in run
    self._run()
  File "mrjob/dataproc.py", line 434, in _run
    self._launch()
  File "mrjob/dataproc.py", line 439, in _launch
    self._launch_cluster()
  File "mrjob/dataproc.py", line 709, in _launch_cluster
    self._api_cluster_create(cluster_data)
  File "mrjob/dataproc.py", line 1089, in _api_cluster_create
    body=cluster_data
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/googleapiclient/http.py", line 838, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://dataproc.googleapis.com/v1/projects/mrjob-testing/regions/global/clusters?alt=json returned "The resource 'projects/mrjob-testing/global/networks/default' was not found">
```

which was fixed by running `gcloud compute networks create default`.

This is a pretty cryptic error message; it seems like it's something mrjob should be able to resolve itself.

**Comment by davidmarin** [comment]
This seems to be no longer an issue. Thanks, `gcloud`.

**Comment by davidmarin** [comment]
This now needs to be done in the cloud console, prior to downloading credentials.

**Comment by davidmarin** [comment]
It looks like this happens automatically when you enable Google Cloud Dataproc in the console.
