### ISSUE TITLE
ValueError: Bad --steps response:

### ISSUE THREAD

**Issue by SKumarMN** [Yelp/mrjob#1500]
Hi,

I am trying to execute the below program  on windows 7 using **-r local** as the input param and getting the below error. However if i dont pass -r local, it works fine

My program
**mrcc.py**

`
import gzip
import boto
import warc
from boto.s3.key import Key
from gzipstream import GzipStreamFile
from mrjob.job import MRJob
from mrjob.protocol import RawProtocol

```
class CCJob(MRJob):
 
  def process_record(self, record):
   raise NotImplementedError('Process record needs to be customized')

  def mapper(self, _, line):
    f = None
    if self.options.runner in ['emr', 'hadoop']:
     
      conn = boto.connect_s3(anon=True)
      pds = conn.get_bucket('aws-publicdatasets')
    
      k = Key(pds, line)
      f = warc.WARCFile(fileobj=GzipStreamFile(k))
    
    else:
      print 'Loading local file {}'.format(line)
      f = warc.WARCFile(fileobj=gzip.open(line))
    ###
    for i, record in enumerate(f):
      for key, value in self.process_record(record):
        yield key, value
      self.increment_counter('commoncrawl', 'processed_records', 1)

  def reducer(self, key, value):
    yield key, sum(value)
```

`

**tagcounter.py**

```
import re
from collections import Counter
from mrcc import CCJob


class TagCounter(CCJob):

  def process_record(self, record):

    if record['Content-Type'] == 'application/http; msgtype=response':
      yield record['WARC-Target-URI'], 1

if __name__ == "__main__":
  TagCounter.run()
```
Executioncommand:

`python tagcounter.py  -r local --conf-path mrjob.conf --no-output --output-dir out init.txt`

**Error**
Traceback (most recent call last):
  File "tagcounter.py", line 22, in <module>
    TagCounter.run()
  File "C:\mnsk\anaconda\lib\site-packages\mrjob\job.py", line 429, in run
    mr_job.execute()
  File "C:\mnsk\anaconda\lib\site-packages\mrjob\job.py", line 447, in execute
    super(MRJob, self).execute()
  File "C:\mnsk\anaconda\lib\site-packages\mrjob\launch.py", line 158, in execute
    self.run_job()
  File "C:\mnsk\anaconda\lib\site-packages\mrjob\launch.py", line 228, in run_job
    runner.run()
  File "C:\mnsk\anaconda\lib\site-packages\mrjob\runner.py", line 481, in run
    self._run()
  File "C:\mnsk\anaconda\lib\site-packages\mrjob\sim.py", line 179, in _run
    for step_num, step in enumerate(self._get_steps()):
  File "C:\mnsk\anaconda\lib\site-packages\mrjob\runner.py", line 752, in _get_steps
    raise ValueError("Bad --steps response: \n%s" % stdout)
ValueError: Bad --steps response:
hi
[{"mapper": {"type": "script"}, "reducer": {"type": "script"}, "type": "streaming"}]

**Comment by SKumarMN** [comment]
I tried the exact program found in https://github.com/Smerity/cc-mrjob

however i got the below error when running the program with -r local as args

Running step 1 of 1...
Traceback (most recent call last):
  File "tagcounter.py", line 41, in <module>
    TagCounter.run()
  File "C:\mnsk\anaconda\lib\site-packages\mrjob\job.py", line 429, in run
    mr_job.execute()
  File "C:\mnsk\anaconda\lib\site-packages\mrjob\job.py", line 447, in execute
    super(MRJob, self).execute()
  File "C:\mnsk\anaconda\lib\site-packages\mrjob\launch.py", line 158, in execute
    self.run_job()
  File "C:\mnsk\anaconda\lib\site-packages\mrjob\launch.py", line 228, in run_job
    runner.run()
  File "C:\mnsk\anaconda\lib\site-packages\mrjob\runner.py", line 481, in run
    self._run()
  File "C:\mnsk\anaconda\lib\site-packages\mrjob\sim.py", line 186, in _run
    self._invoke_step(step_num, 'mapper')
  File "C:\mnsk\anaconda\lib\site-packages\mrjob\sim.py", line 273, in _invoke_step
    working_dir, env)
  File "C:\mnsk\anaconda\lib\site-packages\mrjob\local.py", line 131, in _run_step
    procs_args, output_path, working_dir, env)
  File "C:\mnsk\anaconda\lib\site-packages\mrjob\local.py", line 234, in _invoke_processes
    cwd=working_dir, env=env)
  File "C:\mnsk\anaconda\lib\site-packages\mrjob\local.py", line 69, in _chain_procs
    proc = Popen(args, **proc_kwargs)
  File "C:\mnsk\anaconda\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "C:\mnsk\anaconda\lib\subprocess.py", line 959, in _execute_child
    startupinfo)
**WindowsError: [Error 2] The system cannot find the file specified**

The file is present and it works fine if the run the program without **-r local** as argument

**Comment by davidmarin** [comment]
You can't use `print` in a mapper; Hadoop Streaming requires that only the output of the job be passed to stdout.

I don't see where in your code the line "hi" is printed to stdout, but that's what's causing the bad `--steps` response.
