### ISSUE TITLE
mrjob failed to start run due to following error

### ISSUE THREAD

**Issue by nalin2009bits** [Yelp/mrjob#1546]
Hi,

I am running an MRJob on Hadoop cluster & I am getting the following error:
```
No configs found; falling back on auto-configuration
Looking for Hadoop binary in $PATH...
Found hadoop binary: /usr/local/hadoop/bin/hadoop
Using Hadoop version 2.7.3
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/mrjob-0.5.8-py3.5.egg/mrjob/runner.py",
line 745, in _get_steps
    steps = json.loads(stdout)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 139)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bhoots21304/Desktop/MrJobs-MR.py", line 36, in <module>
    Top10Movies.run()
  File "/usr/local/lib/python3.5/dist-packages/mrjob-0.5.8-py3.5.egg/mrjob/job.py",
line 439, in run
    mr_job.execute()
  File "/usr/local/lib/python3.5/dist-packages/mrjob-0.5.8-py3.5.egg/mrjob/job.py",
line 460, in execute
    super(MRJob, self).execute()
  File "/usr/local/lib/python3.5/dist-packages/mrjob-0.5.8-py3.5.egg/mrjob/launch.py",
line 161, in execute
    self.run_job()
  File "/usr/local/lib/python3.5/dist-packages/mrjob-0.5.8-py3.5.egg/mrjob/launch.py",
line 231, in run_job
    runner.run()
  File "/usr/local/lib/python3.5/dist-packages/mrjob-0.5.8-py3.5.egg/mrjob/runner.py",
line 476, in run
    self._run()
  File "/usr/local/lib/python3.5/dist-packages/mrjob-0.5.8-py3.5.egg/mrjob/hadoop.py",
line 356, in _run
    self._find_binaries_and_jars()
  File "/usr/local/lib/python3.5/dist-packages/mrjob-0.5.8-py3.5.egg/mrjob/hadoop.py",
line 373, in _find_binaries_and_jars
    if self._has_streaming_steps():
  File "/usr/local/lib/python3.5/dist-packages/mrjob-0.5.8-py3.5.egg/mrjob/runner.py",
line 773, in _has_streaming_steps
    for step in self._get_steps())
  File "/usr/local/lib/python3.5/dist-packages/mrjob-0.5.8-py3.5.egg/mrjob/runner.py",
line 747, in _get_steps
    raise ValueError("Bad --steps response: \n%s" % stdout)
ValueError: Bad --steps response:
[{"type": "streaming", "reducer": {"type": "script"}, "mapper":
{"type": "script"}}, {"type": "streaming", "reducer": {"type":
"script"}}]
Job Execution time: 0.00427875300000001 secs
```

I am running the job via this command : 
python3 /home/bhoots21304/Desktop/MrJobs-MR.py -r hadoop hdfs://input3/File.txt > answer.txt

**Comment by davidmarin** [comment]
Looks like you have a printout in your script somewhere (`Job Execution time: 0.00427875300000001 secs`). This not only confuses mrjob, it'll confuse Hadoop Streaming, which requires that only your job's data be printed to stdout.

If you want debugging printouts, stderr should work fine.
