### ISSUE TITLE
parse step stderr on EMR

### ISSUE THREAD

**Issue by davidmarin** [Yelp/mrjob#1719]
Currently, we are just parsing step syslog, which contains boring errors like:

```
Task Id : attempt_1514594114374_0001_m_000000_2, Status : FAILED
```

The stderr often contains more interesting errors in Java stacktrace form, like:

```
Error: java.lang.NumberFormatException: For input string: "999999999999999"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:583)
        at java.lang.Integer.parseInt(Integer.java:615)
        at org.apache.hadoop.conf.Configuration.getInt(Configuration.java:1258)
        at org.apache.hadoop.mapred.FixedLengthInputFormat.getRecordLength(FixedLengthInputFormat.java:69)
        at org.apache.hadoop.mapred.FixedLengthInputFormat.getRecordReader(FixedLengthInputFormat.java:82)
        at org.apache.hadoop.mapred.MapTask$TrackedRecordReader.<init>(MapTask.java:170)
        at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:433)
        at org.apache.hadoop.mapred.MapTask.run(MapTask.java:344)
        at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
        at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)
```

This can be helpful when diagnosing Hadoop configuration errors.

**Comment by davidmarin** [comment]
It looks like we're already doing this.
