### ISSUE TITLE
no Hadoop streaming jar

### ISSUE THREAD

**Issue by JiqianDong** [Yelp/mrjob#1803]
I have successfully installed hadoop 3.1.0 and mrjob for python 3.6 on Mac OSX Hi Sierra. But when I run a test.py file on hadoop, it says "no Hadoop streaming jar"

Traceback (most recent call last):
  File "word_count.py", line 14, in <module>
    MRWordCounter.run()
  File "/anaconda3/lib/python3.6/site-packages/mrjob/job.py", line 424, in run
    mr_job.execute()
  File "/anaconda3/lib/python3.6/site-packages/mrjob/job.py", line 445, in execute
    super(MRJob, self).execute()
  File "/anaconda3/lib/python3.6/site-packages/mrjob/launch.py", line 185, in execute
    self.run_job()
  File "/anaconda3/lib/python3.6/site-packages/mrjob/launch.py", line 233, in run_job
    runner.run()
  File "/anaconda3/lib/python3.6/site-packages/mrjob/runner.py", line 511, in run
    self._run()
  File "/anaconda3/lib/python3.6/site-packages/mrjob/hadoop.py", line 350, in _run
    self._run_job_in_hadoop()
  File "/anaconda3/lib/python3.6/site-packages/mrjob/hadoop.py", line 407, in _run_job_in_hadoop
    step_args = self._args_for_step(step_num)
  File "/anaconda3/lib/python3.6/site-packages/mrjob/hadoop.py", line 502, in _args_for_step
    return self._args_for_streaming_step(step_num)
  File "/anaconda3/lib/python3.6/site-packages/mrjob/hadoop.py", line 513, in _args_for_streaming_step
    raise Exception('no Hadoop streaming jar')

I have used the streaming3.1.0.jar successfully directly, but MRJOB can not find the directory of it.
How can I add the path of streaming.jar to MRJOB?

**Comment by davidmarin** [comment]
It's looking for a file named something like `hadoop-streaming.jar`; probably it's confused by your jar not having "hadoop" in its name.

If you renamed the jar to "hadoop-streaming3.1.0.jar" it would probably just work. You can also run your job with `--hadoop-streaming-jar <path to JAR>`
