### ISSUE TITLE
Cannot input hdfs path to mrjob on local Hadoop

### ISSUE THREAD

**Issue by akshedu** [Yelp/mrjob#1826]
I think its a straightforward application of the mrjob library. I am not able to use hdfs file input:

```(mrjob) Workspace $ python cc-mrjob/word_count_classic.py --hadoop-streaming-jar /usr/local/Cellar/hadoop/3.1.1/libexec/share/hadoop/tools/lib/hadoop-streaming-3.1.1.jar -r hadoop hdfs:///workspace/pg2701.txt
Using configs in /Users/akshanshgupta/.mrjob.conf
Creating temp directory /var/folders/xz/g4k09fps1bd1vm9r4mj8dgnm0000gn/T/word_count_classic.akshanshgupta.20180830.115026.352538
Archiving /Users/akshanshgupta/Workspace/cc-mrjob/packages -> /var/folders/xz/g4k09fps1bd1vm9r4mj8dgnm0000gn/T/word_count_classic.akshanshgupta.20180830.115026.352538/archives/packages.tar.gz
Looking for hadoop binary in $PATH...
Found hadoop binary: /usr/local/bin/hadoop
STDERR: 2018-08-30 17:20:40,123 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
STDERR: ls: `hdfs:///workspace/pg2701.txt': No such file or directory
Traceback (most recent call last):
  File "cc-mrjob/word_count_classic.py", line 31, in <module>
    MRWordFreqCount.run()
  File "/Users/akshanshgupta/mrjob/lib/python2.7/site-packages/mrjob/job.py", line 436, in run
    mr_job.execute()
  File "/Users/akshanshgupta/mrjob/lib/python2.7/site-packages/mrjob/job.py", line 457, in execute
    super(MRJob, self).execute()
  File "/Users/akshanshgupta/mrjob/lib/python2.7/site-packages/mrjob/launch.py", line 187, in execute
    self.run_job()
  File "/Users/akshanshgupta/mrjob/lib/python2.7/site-packages/mrjob/launch.py", line 235, in run_job
    runner.run()
  File "/Users/akshanshgupta/mrjob/lib/python2.7/site-packages/mrjob/runner.py", line 515, in run
    self._check_input_paths()
  File "/Users/akshanshgupta/mrjob/lib/python2.7/site-packages/mrjob/runner.py", line 1007, in _check_input_paths
    if not self.fs.exists(path):
  File "/Users/akshanshgupta/mrjob/lib/python2.7/site-packages/mrjob/fs/composite.py", line 84, in exists
    return self._do_action('exists', path_glob)
  File "/Users/akshanshgupta/mrjob/lib/python2.7/site-packages/mrjob/fs/composite.py", line 68, in _do_action
    raise first_exception
IOError: Could not check path hdfs:///workspace/pg2701.txt
```

**Comment by davidmarin** [comment]
Huh, that's pretty much what mrjob is doing. If you run your batch with `-v`, it'll show you the `hadoop fs` command it's running.

What happens if you `hadoop fs -ls hdfs:///workspace/pg2701.txt`?

**Comment by user2589** [comment]
@akshedu,

I couldn’t find a better way to contact you so I’m writing here. This comment will be deleted in one week to keep the issue discussion clean.

My name is Marat, I am a PhD student at Carnegie Mellon University. As a part of my research, I’m trying to better understand the sources of issue reports in open source.

Can you please help me by answering few questions about this issue? It shouldn’t take more than a couple of minutes. Here’s the google form: [link](https://docs.google.com/forms/d/e/1FAIpQLSfTlhMeh25AZAr0wy-DNBki_HzFP_fqdT3eIk1mf7b80mg8Lg/viewform?usp=pp_url&entry.2074867396=https://github.com/Yelp/mrjob/issues/1826)

I will share everything I learn from answers to this survey with the community afterwards.

Thank you very much!
