### ISSUE TITLE
fail gracefully if S3 input files are in Glacier

### ISSUE THREAD

**Issue by davidmarin** [Yelp/mrjob#1887]
`check_input_paths` should check if input files are in Glacier and issue a reasonable error message if so.

**Comment by davidmarin** [comment]
Got as far as creating a Glacier-archived file and trying to run wordcount on it

**Comment by davidmarin** [comment]
One of the issues is that a file that's restored from Glacier is only restored temporarily. A file that expires in, say, one minute, is not much more useful than one that's fully archived.

**Comment by davidmarin** [comment]
Here's the error you get when trying to read a glacier-archived input file:

```
Exception running child : java.io.IOException: com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.services.s3.model.AmazonS3Exception: The operation is not valid for the object's storage class (Service: Amazon S3; Status Code: 403; Error Code: InvalidObjectState; Request ID: 25831B4146C8645E; S3 Extended Request ID: n73unxX/a03XRdy/AfGReQm6/Ad4RgF8RNFFh7QlLyK9Xz/SxeGPcaN01HgehimBmy7PS15f1/0=), S3 Extended Request ID: n73unxX/a03XRdy/AfGReQm6/Ad4RgF8RNFFh7QlLyK9Xz/SxeGPcaN01HgehimBmy7PS15f1/0=
	at com.amazon.ws.emr.hadoop.fs.s3n.Jets3tNativeFileSystemStore.handleAmazonServiceException(Jets3tNativeFileSystemStore.java:448)
	at com.amazon.ws.emr.hadoop.fs.s3n.Jets3tNativeFileSystemStore.retrievePair(Jets3tNativeFileSystemStore.java:476)
	at com.amazon.ws.emr.hadoop.fs.s3n.Jets3tNativeFileSystemStore.retrievePair(Jets3tNativeFileSystemStore.java:453)
	at com.amazon.ws.emr.hadoop.fs.s3n.S3NativeFileSystem.open(S3NativeFileSystem.java:1127)
	at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:790)
	at com.amazon.ws.emr.hadoop.fs.EmrFileSystem.open(EmrFileSystem.java:192)
	at org.apache.hadoop.mapred.LineRecordReader.<init>(LineRecordReader.java:109)
	at org.apache.hadoop.mapred.TextInputFormat.getRecordReader(TextInputFormat.java:67)
	at org.apache.hadoop.mapred.MapTask$TrackedRecordReader.<init>(MapTask.java:170)
	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:433)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:344)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1840)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)
Caused by: com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.services.s3.model.AmazonS3Exception: The operation is not valid for the object's storage class (Service: Amazon S3; Status Code: 403; Error Code: InvalidObjectState; Request ID: 25831B4146C8645E; S3 Extended Request ID: n73unxX/a03XRdy/AfGReQm6/Ad4RgF8RNFFh7QlLyK9Xz/SxeGPcaN01HgehimBmy7PS15f1/0=), S3 Extended Request ID: n73unxX/a03XRdy/AfGReQm6/Ad4RgF8RNFFh7QlLyK9Xz/SxeGPcaN01HgehimBmy7PS15f1/0=
	at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1632)
	at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1304)
	at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1058)
	at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4365)
	at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4312)
	at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1415)
	at com.amazon.ws.emr.hadoop.fs.s3.lite.call.GetObjectCall.perform(GetObjectCall.java:22)
	at com.amazon.ws.emr.hadoop.fs.s3.lite.call.GetObjectCall.perform(GetObjectCall.java:9)
	at com.amazon.ws.emr.hadoop.fs.s3.lite.executor.GlobalS3Executor.execute(GlobalS3Executor.java:91)
	at com.amazon.ws.emr.hadoop.fs.s3.lite.AmazonS3LiteClient.invoke(AmazonS3LiteClient.java:185)
	at com.amazon.ws.emr.hadoop.fs.s3.lite.AmazonS3LiteClient.getObject(AmazonS3LiteClient.java:102)
	at com.amazon.ws.emr.hadoop.fs.s3n.Jets3tNativeFileSystemStore.retrievePair(Jets3tNativeFileSystemStore.java:466)
	... 14 more
```

**Comment by davidmarin** [comment]
I don't think we really need to worry about expiration. Even if a job runs a long time, the time to ingest input is usually rather short. The main use case is to catch a job that mistakenly reads from Glacier-archived input before it runs and spits out a cryptic error message.

**Comment by davidmarin** [comment]
Whoops, apparently restored objects still have storage class `GLACIER`. Need some other way of identifying objects which are Glacier-archived but have been restored.

**Comment by davidmarin** [comment]
Looks like I need to look at the `restore` field of the `S3Object`. Something like `'ongoing-request="false", expiry-date="Sun, 23 Dec 2018 00:00:00 GMT"'` indicates that the object is still available.
