### ISSUE TITLE
"ImportError: cannot import name SIGKILL" on creating cluster using Windows

### ISSUE THREAD

**Issue by marksimpson82** [Yelp/mrjob#1892]
**Dev environment**
Windows 10 Professional, 64-bit, Version 1803
Python 2.7.14, 64-bit

**Mrjob Version**
0.6.3 onwards. Have reproduced the issue on 0.6.3 & 0.6.6

**Repro Steps**
Try to launch an AWS EMR cluster via:
`mrjob-2.7 create-cluster`

**Expected Behaviour**
Cluster should launch

**Observed Behaviour**
Cluster fails to launch. Stack trace:
```
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\mrjob-2.7.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\mrjob\cmd.py", line 68, in main
    commands[args[1]](args[2:])
  File "c:\python27\lib\site-packages\mrjob\cmd.py", line 85, in _create_cluster
    from mrjob.tools.emr.create_cluster import main
  File "c:\python27\lib\site-packages\mrjob\tools\emr\create_cluster.py", line 198, in <module>
    from mrjob.emr import EMRJobRunner
  File "c:\python27\lib\site-packages\mrjob\emr.py", line 52, in <module>
    from mrjob.cloud import HadoopInTheCloudJobRunner
  File "c:\python27\lib\site-packages\mrjob\cloud.py", line 23, in <module>
    from signal import SIGKILL
ImportError: cannot import name SIGKILL
```

**Additional Details**
mrjob 0.6.2 works

The SIGKILL was possibly introduced here (0.6.3), but not 100%: 
https://github.com/Yelp/mrjob/commit/6002657296af57488f6069186c71e5d4259fd619

**Comment by davidmarin** [comment]
Aha. Looks pretty easy to fix. Thanks for pointing this out.
