### ISSUE TITLE
Unable to create cluster in us-east-1

### ISSUE THREAD

**Issue by fizerkhan** [Yelp/mrjob#1927]
I am trying to create cluster in `us-east-1`  region. It throws an error.

Version: `mrjob (0.6.6)`

```
ubuntu@ip-172-31-12-166:~/test-mrjobs$ mrjob create-cluster --max-mins-idle 30 --region us-east-1
Using configs in /etc/mrjob.conf
Auto-created temp S3 bucket mrjob-f8b911f04c613c8b
Using s3://mrjob-f8b911f04c613c8b/tmp/ as our temp dir on S3
Creating persistent cluster to run several jobs in...
Creating temp directory /tmp/no_script.ubuntu.20181231.110845.652462
writing master bootstrap script to /tmp/no_script.ubuntu.20181231.110845.652462/b.sh
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/mrjob", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python2.7/site-packages/mrjob/cmd.py", line 68, in main
    commands[args[1]](args[2:])
  File "/home/ubuntu/.local/lib/python2.7/site-packages/mrjob/cmd.py", line 86, in _create_cluster
    main(args)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/mrjob/tools/emr/create_cluster.py", line 210, in main
    cluster_id = runner.make_persistent_cluster()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/mrjob/emr.py", line 2318, in make_persistent_cluster
    self._upload_local_files_to_s3()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/mrjob/emr.py", line 821, in _upload_local_files_to_s3
    self._create_s3_tmp_bucket_if_needed()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/mrjob/emr.py", line 633, in _create_s3_tmp_bucket_if_needed
    self._opts['region'])
  File "/home/ubuntu/.local/lib/python2.7/site-packages/mrjob/fs/s3.py", line 391, in create_bucket
    CreateBucketConfiguration=conf)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/mrjob/retry.py", line 90, in call_and_maybe_retry
    return f(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (MalformedXML) when calling the CreateBucket operation: The XML you provided was not well-formed or did not validate against our published schema
```

How do I resolve this issue?

**Comment by davidmarin** [comment]
Was able to duplicate this error, fixing now. Thank you so much for noticing this.

**Comment by davidmarin** [comment]
looks like `CreateBucketConfiguration` can't be empty; if we don't want a location constraint, we shouldn't set the configuration either. That's what's causing `MalformedXML`.

**Comment by davidmarin** [comment]
Also, it looks like there's a race condition with the the temp bucket (`NoSuchBucket` when checking the newly created bucket's location constraint).
