### ISSUE TITLE
Tutorial failed. 'worldcount' on Hadoop error.

### ISSUE THREAD

**Issue by HengyueLi** [Yelp/mrjob#2012]
I tried the worldcount on hadoop (EMR on AWS).  I get the following error:

    No configs found; falling back on auto-configuration
    No configs specified for hadoop runner
    Looking for hadoop binary in $PATH...
    Found hadoop binary: /usr/bin/hadoop
    Using Hadoop version 2.8.5
    Looking for Hadoop streaming jar in /home/hadoop/contrib...
    Looking for Hadoop streaming jar in /usr/lib/hadoop-mapreduce...
    Found Hadoop streaming jar: /usr/lib/hadoop-mapreduce/hadoop-streaming.jar
    Creating temp directory /tmp/job.hadoop.20190308.072655.534249
    Copying local files to hdfs:///user/hadoop/tmp/mrjob/job.hadoop.20190308.072655.534249/files/...
    Running step 1 of 1...
      packageJobJar: [] [/usr/lib/hadoop/hadoop-streaming-2.8.5-amzn-1.jar] /tmp/streamjob980641666367265385.jar tmpDir=null
      Connecting to ResourceManager at ip-172-31-36-214.cn-northwest-1.compute.internal/172.31.36.214:8032
      Connecting to ResourceManager at ip-172-31-36-214.cn-northwest-1.compute.internal/172.31.36.214:8032
      Loaded native gpl library
      Successfully loaded & initialized native-lzo library [hadoop-lzo rev 1546b8dc0ca6f1ffd26a812d52bd7b80915e0a25]
      Total input files to process : 1
      number of splits:8
      Submitting tokens for job: job_1552029614392_0008
      Submitted application application_1552029614392_0008
      The url to track the job: http://ip-172-31-36-214.cn-northwest-1.compute.internal:20888/proxy/application_1552029614392_0008/
      Running job: job_1552029614392_0008
      Job job_1552029614392_0008 running in uber mode : false
       map 0% reduce 0%
      Task Id : attempt_1552029614392_0008_m_000004_0, Status : FAILED
    Error: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 2
    	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:325)
    	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:538)
    	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
    	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
    	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
    	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:455)
    	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:344)
    	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at javax.security.auth.Subject.doAs(Subject.java:422)
    	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1844)
    	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)

      Task Id : attempt_1552029614392_0008_m_000005_0, Status : FAILED
    Error: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 2
    	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:325)
    	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:538)
    	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
    	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
    	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
    	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:455)
    	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:344)
    	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at javax.security.auth.Subject.doAs(Subject.java:422)
    	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1844)
    	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)

      Task Id : attempt_1552029614392_0008_m_000000_0, Status : FAILED
    Error: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 2
    	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:325)
    	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:538)
    	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
    	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
    	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
    	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:455)
    	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:344)
    	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at javax.security.auth.Subject.doAs(Subject.java:422)
    	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1844)
    	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)

      Task Id : attempt_1552029614392_0008_m_000002_0, Status : FAILED
    Error: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 2
    	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:325)
    	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:538)
    	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
    	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
    	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
    	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:455)
    	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:344)
    	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at javax.security.auth.Subject.doAs(Subject.java:422)
    	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1844)
    	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)

      Task Id : attempt_1552029614392_0008_m_000003_0, Status : FAILED
    Error: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 2
    	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:325)
    	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:538)
    	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
    	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
    	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
    	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:455)
    	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:344)
    	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at javax.security.auth.Subject.doAs(Subject.java:422)
    	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1844)
    	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)

      Task Id : attempt_1552029614392_0008_m_000001_0, Status : FAILED
    Error: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 2
    	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:325)
    	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:538)
    	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
    	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
    	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
    	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:455)
    	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:344)
    	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at javax.security.auth.Subject.doAs(Subject.java:422)
    	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1844)
    	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)

      Task Id : attempt_1552029614392_0008_m_000004_1, Status : FAILED
    Error: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 2
    	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:325)
    	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:538)
    	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
    	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
    	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
    	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:455)
    	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:344)
    	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at javax.security.auth.Subject.doAs(Subject.java:422)
    	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1844)
    	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)

      Task Id : attempt_1552029614392_0008_m_000005_1, Status : FAILED
    Error: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 2
    	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:325)
    	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:538)
    	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
    	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
    	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
    	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:455)
    	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:344)
    	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at javax.security.auth.Subject.doAs(Subject.java:422)
    	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1844)
    	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)

      Task Id : attempt_1552029614392_0008_m_000000_1, Status : FAILED
    Error: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 2
    	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:325)
    	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:538)
    	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
    	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
    	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
    	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:455)
    	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:344)
    	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at javax.security.auth.Subject.doAs(Subject.java:422)
    	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1844)
    	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)

      Task Id : attempt_1552029614392_0008_m_000003_1, Status : FAILED
    Error: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 2
    	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:325)
    	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:538)
    	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
    	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
    	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
    	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:455)
    	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:344)
    	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at javax.security.auth.Subject.doAs(Subject.java:422)
    	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1844)
    	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)

      Task Id : attempt_1552029614392_0008_m_000002_1, Status : FAILED
    Error: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 2
    	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:325)
    	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:538)
    	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
    	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
    	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
    	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:455)
    	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:344)
    	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at javax.security.auth.Subject.doAs(Subject.java:422)
    	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1844)
    	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)

      Task Id : attempt_1552029614392_0008_m_000001_1, Status : FAILED
    Error: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 2
    	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:325)
    	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:538)
    	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
    	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
    	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
    	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:455)
    	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:344)
    	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at javax.security.auth.Subject.doAs(Subject.java:422)
    	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1844)
    	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)

      Task Id : attempt_1552029614392_0008_m_000000_2, Status : FAILED
    Error: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 2
    	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:325)
    	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:538)
    	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
    	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
    	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
    	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:455)
    	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:344)
    	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at javax.security.auth.Subject.doAs(Subject.java:422)
    	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1844)
    	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)

      Task Id : attempt_1552029614392_0008_m_000004_2, Status : FAILED
    Error: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 2
    	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:325)
    	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:538)
    	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
    	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
    	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
    	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:455)
    	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:344)
    	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at javax.security.auth.Subject.doAs(Subject.java:422)
    	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1844)
    	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)

      Task Id : attempt_1552029614392_0008_m_000003_2, Status : FAILED
    Error: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 2
    	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:325)
    	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:538)
    	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
    	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
    	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
    	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:455)
    	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:344)
    	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at javax.security.auth.Subject.doAs(Subject.java:422)
    	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1844)
    	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)

      Task Id : attempt_1552029614392_0008_m_000005_2, Status : FAILED
    Error: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 2
    	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:325)
    	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:538)
    	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
    	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
    	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
    	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:455)
    	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:344)
    	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at javax.security.auth.Subject.doAs(Subject.java:422)
    	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1844)
    	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)

       map 100% reduce 100%
      Job job_1552029614392_0008 failed with state FAILED due to: Task failed task_1552029614392_0008_m_000000
    Job failed as tasks failed. failedMaps:1 failedReduces:0

      Job not successful!
      Streaming Command Failed!
    Counters: 18
    	Job Counters 
    		Data-local map tasks=4
    		Failed map tasks=17
    		Killed map tasks=7
    		Killed reduce tasks=3
    		Launched map tasks=22
    		Other local map tasks=16
    		Rack-local map tasks=2
    		Total megabyte-milliseconds taken by all map tasks=289718784
    		Total megabyte-milliseconds taken by all reduce tasks=0
    		Total time spent by all map tasks (ms)=188619
    		Total time spent by all maps in occupied slots (ms)=9053712
    		Total time spent by all reduce tasks (ms)=0
    		Total time spent by all reduces in occupied slots (ms)=0
    		Total vcore-milliseconds taken by all map tasks=188619
    		Total vcore-milliseconds taken by all reduce tasks=0
    	Map-Reduce Framework
    		CPU time spent (ms)=0
    		Physical memory (bytes) snapshot=0
    		Virtual memory (bytes) snapshot=0
    Scanning logs for probable cause of failure...
    Looking for history log in hdfs:///tmp/hadoop-yarn/staging...
      Parsing history log: hdfs:///tmp/hadoop-yarn/staging/history/done/2019/03/08/000000/job_1552029614392_0008-1552030036490-hadoop-streamjob980641666367265385.jar-1552030085244-0-0-FAILED-default-1552030044997.jhist
    Probable cause of failure:

    Error: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 2
    	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:325)
    	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:538)
    	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
    	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
    	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
    	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:455)
    	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:344)
    	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at javax.security.auth.Subject.doAs(Subject.java:422)
    	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1844)
    	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)

    (from line 111 of hdfs:///tmp/hadoop-yarn/staging/history/done/2019/03/08/000000/job_1552029614392_0008-1552030036490-hadoop-streamjob980641666367265385.jar-1552030085244-0-0-FAILED-default-1552030044997.jhist)

    Step 1 of 1 failed: Command '['/usr/bin/hadoop', 'jar', '/usr/lib/hadoop-mapreduce/hadoop-streaming.jar', '-files', 'hdfs:///user/hadoop/tmp/mrjob/job.hadoop.20190308.072655.534249/files/job.py#job.py,hdfs:///user/hadoop/tmp/mrjob/job.hadoop.20190308.072655.534249/files/mrjob.zip#mrjob.zip,hdfs:///user/hadoop/tmp/mrjob/job.hadoop.20190308.072655.534249/files/setup-wrapper.sh#setup-wrapper.sh', '-input', 'hdfs:///user/hadoop/tmp/mrjob/job.hadoop.20190308.072655.534249/files/input.txt', '-output', 'hdfs:///user/hadoop/tmp/mrjob/job.hadoop.20190308.072655.534249/output', '-mapper', '/bin/sh -ex setup-wrapper.sh python3 job.py --step-num=0 --mapper', '-combiner', '/bin/sh -ex setup-wrapper.sh python3 job.py --step-num=0 --combiner', '-reducer', '/bin/sh -ex setup-wrapper.sh python3 job.py --step-num=0 --reducer']' returned non-zero exit status 256.

**Comment by HengyueLi** [comment]
The problem is still about the version of AMI of AWS. (Refer [here](https://stackoverflow.com/questions/41945368/mrjob-does-not-work-on-amazon-emr-5-x-but-does-run-on-emr4-8-3).) A older version of EMR is working well.
