### ISSUE TITLE
(mid-release-issue) error when uploading to s3 with no part_size

### ISSUE THREAD

**Issue by davidmarin** [Yelp/mrjob#2033]
We're getting an error in the Spark runner inside `s3transfer`, where it tries to compare the requested part size (`None`) to an integer:

```
Traceback (most recent call last):
  File "/spark_driver/mr_most_used_word.py", line 53, in <module>
    MRMostUsedWord.run()
  File "/work/mrjob/mrjob/job.py", line 438, in run
    mr_job.execute()
  File "/work/mrjob/mrjob/job.py", line 465, in execute
    super(MRJob, self).execute()
  File "/work/mrjob/mrjob/launch.py", line 190, in execute
    self.run_job()
  File "/work/mrjob/mrjob/launch.py", line 235, in run_job
    runner.run()
  File "/work/mrjob/mrjob/runner.py", line 513, in run
    self._run()
  File "/work/mrjob/mrjob/spark/runner.py", line 139, in _run
    self._upload_local_files()
  File "/work/mrjob/mrjob/runner.py", line 1156, in _upload_local_files
    self.fs.put(src_path, uri)
  File "/work/mrjob/mrjob/fs/composite.py", line 159, in put
    return self._handle('put', path, src, path)
  File "/work/mrjob/mrjob/fs/composite.py", line 118, in _handle
    return getattr(fs, name)(*args, **kwargs)
  File "/work/mrjob/mrjob/fs/s3.py", line 274, in put
    multipart_threshold=self._part_size,
  File "/work/venv/lib/python3.6/site-packages/boto3/s3/inject.py", line 280, in object_upload_file
    ExtraArgs=ExtraArgs, Callback=Callback, Config=Config)
  File "/work/mrjob/mrjob/retry.py", line 90, in call_and_maybe_retry
    return f(*args, **kwargs)
  File "/work/venv/lib/python3.6/site-packages/boto3/s3/inject.py", line 131, in upload_file
    extra_args=ExtraArgs, callback=Callback)
  File "/work/venv/lib/python3.6/site-packages/boto3/s3/transfer.py", line 279, in upload_file
    future.result()
  File "/work/venv/lib/python3.6/site-packages/s3transfer/futures.py", line 73, in result
    return self._coordinator.result()
  File "/work/venv/lib/python3.6/site-packages/s3transfer/futures.py", line 233, in result
    raise self._exception
  File "/work/venv/lib/python3.6/site-packages/s3transfer/tasks.py", line 255, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "/work/venv/lib/python3.6/site-packages/s3transfer/upload.py", line 553, in _submit
    transfer_future, config):
  File "/work/venv/lib/python3.6/site-packages/s3transfer/upload.py", line 240, in requires_multipart_upload
    return transfer_future.meta.size >= config.multipart_threshold
TypeError: '>=' not supported between instances of 'int' and 'NoneType'
```

Need to try to duplicate this bug, patch it, and upload our test framework to raise this error if we undo the patch in the future.

**Comment by davidmarin** [comment]
You can trigger this on EMR by running with `--cloud-part-size-mb 0`.

Should probably also set a default part size on Spark.

**Comment by davidmarin** [comment]
This wasn't an issue prior to this release because we'd use `_HUGE_PART_THRESHOLD` to disable multipart upload.

**Comment by davidmarin** [comment]
we probably want to bring `_HUGE_PART_THRESHOLD` back, at least on s3. If you don't specify a transfer config, `boto3` uses the default one, which has a part size of 8 MB.

**Comment by davidmarin** [comment]
This isn't an issue on Google Cloud Storage; the relevant library only does a multipart upload if you specify a part size. See https://github.com/googleapis/google-cloud-python/blob/master/storage/google/cloud/storage/blob.py#L1016
