### ISSUE TITLE
ArchiveTestCase has several failures on OS X under Python 2.5

### ISSUE THREAD

**Issue by irskep** [Yelp/mrjob#276]
Pretty much like this:

    tests.util_test ArchiveTestCase.test_unarchive_tar
    Traceback (most recent call last):
      File "./tests/util_test.py", line 320, in test_unarchive_tar
        ['tar', 'chf', '%(archive_name)s', '%(files_to_archive)s'])
      File "./tests/util_test.py", line 314, in archive_and_unarchive
        self.ensure_expected_results(added_files=added_files)
      File "./tests/util_test.py", line 257, in ensure_expected_results
        sorted(expected_files))
    AssertionError: assertion failed: l == r
    l: ['PaxHeader', 'bar', 'baz', 'foo', 'qux']
    r: ['bar', 'baz', 'foo', 'qux']

    Diff:
    l: <['PaxHeader', >'bar', 'baz', 'foo', 'qux']
    r: <[>'bar', 'baz', 'foo', 'qux']

This only happens under Python 2.5.

**Comment by davidmarin** [comment]
Support for 2.5 has been dropped!
