### ISSUE TITLE
use multipart upload for large files

### ISSUE THREAD

**Issue by rspeer** [Yelp/mrjob#309]
When I try to process a 40 GB file with mrjob, it crashes during the uploading step with a "broken pipe" error.

If this is the wrong way to feed 40 GB of data into mrjob, there should be some sort of warning about that, and a pointer to the right way to do it. I'm currently manually uploading the data to S3 as a workaround.

```
python corona.py -r emr --enable-emr-debugging inputs/edges.json > inputs/conceptnet_emr.txt
using configs in /Users/rspeer/.mrjob.confUploading input to s3://mimas/tmp/corona.rspeer.20111214.030956.203606/input/
Traceback (most recent call last):
  File "corona.py", line 114, in <module>
    CORONAForwardStep.run()
  File "/Users/rspeer/py/csc/lib/python2.6/site-packages/mrjob/job.py", line 516, in run
    mr_job.execute()
  File "/Users/rspeer/py/csc/lib/python2.6/site-packages/mrjob/job.py", line 532, in execute
    self.run_job()
  File "/Users/rspeer/py/csc/lib/python2.6/site-packages/mrjob/job.py", line 582, in run_job
    runner.run()
  File "/Users/rspeer/py/csc/lib/python2.6/site-packages/mrjob/runner.py", line 495, in run
    self._run()
  File "/Users/rspeer/py/csc/lib/python2.6/site-packages/mrjob/emr.py", line 836, in _run
    self._prepare_for_launch()
  File "/Users/rspeer/py/csc/lib/python2.6/site-packages/mrjob/emr.py", line 842, in _prepare_for_launch
    self._setup_input()
  File "/Users/rspeer/py/csc/lib/python2.6/site-packages/mrjob/emr.py", line 883, in _setup_input
    s3_key.set_contents_from_filename(path)
  File "/Users/rspeer/py/csc/lib/python2.6/site-packages/boto/s3/key.py", line 857, in set_contents_from_filename
    encrypt_key=encrypt_key)
  File "/Users/rspeer/py/csc/lib/python2.6/site-packages/boto/s3/key.py", line 790, in set_contents_from_file
    self.send_file(fp, headers, cb, num_cb, query_args)
  File "/Users/rspeer/py/csc/lib/python2.6/site-packages/boto/s3/key.py", line 583, in send_file
    query_args=query_args)
  File "/Users/rspeer/py/csc/lib/python2.6/site-packages/boto/s3/connection.py", line 429, in make_request
    override_num_retries=override_num_retries)
  File "/Users/rspeer/py/csc/lib/python2.6/site-packages/boto/connection.py", line 796, in make_request
    return self._mexe(http_request, sender, override_num_retries)
  File "/Users/rspeer/py/csc/lib/python2.6/site-packages/boto/connection.py", line 762, in _mexe
    raise e
socket.error: [Errno 32] Broken pipe
```

**Comment by davidmarin** [comment]
This was added in 0.4.3 (requires `filechunkio`), though it somehow managed not to get an issue number or a listing in CHANGES.txt.
