### ISSUE TITLE
hdfs  paths get empty host specifier stripped when using add_file_option.

### ISSUE THREAD

**Issue by sirusdv** [Yelp/mrjob#767]
HDFS paths such as hdfs:///user/asdf/big.data end up getting transformed in to hdfs://user/asdf/big.data resulting in a "java.lang.IllegalArgumentException: java.net.UnknownHostException: user" exception.

**Comment by kedark3** [comment]
I am facing the issue of non-zero exit status: 256

`Probable cause of failure:

Error: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 1
	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:325)
	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:538)
	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:453)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1693)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)

Step 1 of 5 failed: Command '['/usr/bin/hadoop', 'jar', '/usr/lib/hadoop-mapreduce/hadoop-streaming.jar', '-files', 'hdfs:///user/kkulkar3/tmp/mrjob/movieRecommendation.kkulkar3.20161026.020000.218427/files/setup-wrapper.sh#setup-wrapper.sh,hdfs:///user/kkulkar3/tmp/mrjob/movieRecommendation.kkulkar3.20161026.020000.218427/files/movieRecommendation.py#movieRecommendation.py', '-archives', 'hdfs:///user/kkulkar3/tmp/mrjob/movieRecommendation.kkulkar3.20161026.020000.218427/files/mrjob.tar.gz#mrjob.tar.gz', '-input', 'hdfs:///user/kkulkar3/tmp/mrjob/movieRecommendation.kkulkar3.20161026.020000.218427/files/movies.dat', '-input', 'hdfs:///user/kkulkar3/tmp/mrjob/movieRecommendation.kkulkar3.20161026.020000.218427/files/ratings.dat', '-output', 'hdfs:///user/kkulkar3/tmp/mrjob/movieRecommendation.kkulkar3.20161026.020000.218427/step-output/0000', '-mapper', "sh -ex setup-wrapper.sh python movieRecommendation.py --step-num=0 --mapper -m 'Her (2013)' -m 'Bridge of Spies (2015)'", '-reducer', "sh -ex setup-wrapper.sh python movieRecommendation.py --step-num=0 --reducer -m 'Her (2013)' -m 'Bridge of Spies (2015)'"]' returned non-zero exit status 256`

Can you please help??

**Comment by davidmarin** [comment]
@kedark3 Your problem doesn't seem to be this bug; all the `hdfs:///` paths seem to have three slashes.

Do you know where the log files for this job are? The Python traceback that caused the error should be in a file named `stderr` (or `stderr.gz`).

**Comment by kedark3** [comment]
I don't know where can I find stderr log, could you point it out?
