### ISSUE TITLE
mrjob failed to start run due to bad steps response.

### ISSUE THREAD

**Issue by ravitejareddy** [Yelp/mrjob#787]
I am trying to do elastic search indexing using mrjob and But the job is getting failed due to bad steps response. I didn't understand what that error means. my program looks like below.

program:

```python
import pyes
from mrjob.job import MRJob
from mrjob.protocol import RawProtocol, ReprProtocol
class elasticsearch(MRJob):
    def mapper(self, key, each_line):
        """ config steps"""
        yield (id, str(temp_json))
    def combiner(self, id, temp_json):
        yield (id, temp_json)
    def reducer(self, id, temp_json):
        """ Final indexing Steps"""
if __name__ == '__main__':
    """  Inititalization steps """
    elasticsearch.run()
```

output:

```
Traceback (most recent call last):
  File "pyes_mrjob.py", line 50, in <module>
    elasticsearch.run()
  File "/usr/local/lib/python2.7/dist-packages/mrjob/job.py", line 500, in run
    mr_job.execute()
  File "/usr/local/lib/python2.7/dist-packages/mrjob/job.py", line 518, in execute
    super(MRJob, self).execute()
  File "/usr/local/lib/python2.7/dist-packages/mrjob/launch.py", line 146, in execute
    self.run_job()
  File "/usr/local/lib/python2.7/dist-packages/mrjob/launch.py", line 207, in run_job
    runner.run()
  File "/usr/local/lib/python2.7/dist-packages/mrjob/runner.py", line 458, in run
    self._run()
  File "/usr/local/lib/python2.7/dist-packages/mrjob/hadoop.py", line 237, in _run
    self._run_job_in_hadoop()
  File "/usr/local/lib/python2.7/dist-packages/mrjob/hadoop.py", line 293, in _run_job_in_hadoop
    for step_num in xrange(self._num_steps()):
  File "/usr/local/lib/python2.7/dist-packages/mrjob/runner.py", line 742, in _num_steps
    return len(self._get_steps())
  File "/usr/local/lib/python2.7/dist-packages/mrjob/runner.py", line 721, in _get_steps
    raise ValueError("Bad --steps response: \n%s" % stdout)
ValueError: Bad --steps response: 
[{"mapper": {"type": "script"}, "reducer": {"type": "script"}, "combiner": {"type": "script"}, "type": "streaming"}]
```

Command used to run job:
python pyes_mrjob.py -r hadoop --hadoop-bin /usr/bin/hadoop --jobconf mapred.reduce.tasks=10 -o hdfs:///user/root/output-mrjob hdfs:///user/root/input.txt

I tried steps . 
# python pyes_mrjob.py --steps

[{"mapper": {"type": "script"}, "reducer": {"type": "script"}, "combiner": {"type": "script"}, "type": "streaming"}]

and no logs are available to debug also.

**Comment by davidmarin** [comment]
Closing as a non-issue.
