### ISSUE TITLE
Fails to setup working dir for mapreducer which is extended by another one

### ISSUE THREAD

**Issue by jbasko** [Yelp/mrjob#802]
I used to have one mapreducer X (which lives in x.py) which was working fine.
Now I added another mapreducer SomethingX which extends X and lives in something_x.py where there is "import x".
This breaks mapreducer X in mapper_final stage with the following error.
Could it be that mrjob doesn't do a great job in generating temporary names?

```
2013-10-30 17:09:07,956 [INFO] ... mapper_final
Traceback (most recent call last):
  File "do_run.py", line 23, in <module>
    class_obj.run()
  File ".../venv/lib/python2.7/site-packages/mrjob-0.4.1-py2.7.egg/mrjob/job.py", line 500, in run
    mr_job.execute()
  File ".../venv/lib/python2.7/site-packages/mrjob-0.4.1-py2.7.egg/mrjob/job.py", line 518, in execute
    super(MRJob, self).execute()
  File ".../venv/lib/python2.7/site-packages/mrjob-0.4.1-py2.7.egg/mrjob/launch.py", line 146, in execute
    self.run_job()
  File ".../venv/lib/python2.7/site-packages/mrjob-0.4.1-py2.7.egg/mrjob/launch.py", line 207, in run_job
    runner.run()
  File ".../venv/lib/python2.7/site-packages/mrjob-0.4.1-py2.7.egg/mrjob/runner.py", line 458, in run
    self._run()
  File ".../venv/lib/python2.7/site-packages/mrjob-0.4.1-py2.7.egg/mrjob/sim.py", line 182, in _run
    self._invoke_step(step_num, 'mapper')
  File ".../venv/lib/python2.7/site-packages/mrjob-0.4.1-py2.7.egg/mrjob/sim.py", line 248, in _invoke_step
    self._setup_working_dir(working_dir)
  File ".../venv/lib/python2.7/site-packages/mrjob-0.4.1-py2.7.egg/mrjob/sim.py", line 147, in _setup_working_dir
    self._symlink_to_file_or_copy(path, dest)
  File ".../venv/lib/python2.7/site-packages/mrjob-0.4.1-py2.7.egg/mrjob/sim.py", line 130, in _symlink_to_file_or_copy
    os.symlink(path, dest)
OSError: [Errno 17] File exists
```

**Comment by davidmarin** [comment]
Okay, closing this as a non-issue.
