### ISSUE TITLE
Help,My config seems do not work on my hadoop clauster !!!

### ISSUE THREAD

**Issue by vincentami** [Yelp/mrjob#969]
Hi
   Below is my .mrjob.conf
"
# This is basically the config file we use in production at Yelp, with some
# strategic edits. ;)
#
# If you don't have the yaml module installed, you'll have to use JSON instead,
# which would look something like this:
#
runners:
  hadoop:
    base_tmp_dir: hdfs://lgprc-xxx/user/h_browser/llf/t/tmp
"
I think that there must be something not been configure correctly;
And there is my error log , i do not know why the "mkdir " return failed always here? How the mrjob 
determined the path here?

python mapper.py -r hadoop  --jobconf mapred.reduce.tasks=10 --jobconf mapred.mapper.tasks=10 hdfs://lgprc-xxx/user/h_scribe/mu/mu_browser_ceip/year=2015/month=01/day=30/  --output-dir=hdfs://lgprc-xxx/user/h_browser/llf/t/result/20150130
using configs in /home/work/.mrjob.conf
Got unexpected opts from /home/work/.mrjob.conf: --setup-script
creating tmp directory hdfs://lgprc-xxx/user/h_browser/llf/t/tmp/mapper.work.20150130.075736.835236
writing wrapper script to hdfs://lgprc-xxx/user/h_browser/llf/t/tmp/mapper.work.20150130.075736.835236/setup-wrapper.sh
STDERR: 15/01/30 15:57:39 INFO security.UserGroupInformation: Can't login from keytab, try to login from ticket cache
STDERR: mkdir: `hdfs:///user/work/tmp/mrjob/mapper.work.20150130.075736.835236/files/': No such file or directory
Traceback (most recent call last):
  File "mapper.py", line 317, in <module>
    MRFilterAsRule.run()
  File "/usr/lib/python2.6/site-packages/mrjob/job.py", line 494, in run
    mr_job.execute()
  File "/usr/lib/python2.6/site-packages/mrjob/job.py", line 512, in execute
    super(MRJob, self).execute()
  File "/usr/lib/python2.6/site-packages/mrjob/launch.py", line 147, in execute
    self.run_job()
  File "/usr/lib/python2.6/site-packages/mrjob/launch.py", line 208, in run_job
    runner.run()
  File "/usr/lib/python2.6/site-packages/mrjob/runner.py", line 458, in run
    self._run()
  File "/usr/lib/python2.6/site-packages/mrjob/hadoop.py", line 238, in _run
    self._upload_local_files_to_hdfs()
  File "/usr/lib/python2.6/site-packages/mrjob/hadoop.py", line 265, in _upload_local_files_to_hdfs
    self._mkdir_on_hdfs(self._upload_mgr.prefix)
  File "/usr/lib/python2.6/site-packages/mrjob/hadoop.py", line 273, in _mkdir_on_hdfs
    self.invoke_hadoop(['fs', '-mkdir', path])
  File "/usr/lib/python2.6/site-packages/mrjob/fs/hadoop.py", line 109, in invoke_hadoop
    raise CalledProcessError(proc.returncode, args)
subprocess.CalledProcessError: Command '['/home/work/infra-client/bin/current/lgprc-xxx-hadoop/bin/hadoop', 'fs', '-mkdir', 'hdfs:///user/work/tmp/mrjob/mapper.work.20150130.075736.835236/files/']' returned non-zero exit status 1

And my user name here is work, and the path here "hdfs:///user/work/tmp" is wrong on the hadoop cluster ;

I reviews the mrjob docement ,but it seams that there is no option for that ?

Wish your help.
Thanks a lot .

**Comment by davidmarin** [comment]
`base_tmp_dir` has to be a local directory. Planning to change this to `local_tmp_dir` to avoid confusion (see #318).
