### ISSUE TITLE
Not detecting version correctly using CDH 5 distribution

### ISSUE THREAD

**Issue by dmgening** [Yelp/mrjob#971]
While trying to run job on hadoop using CDH5 distribution mrjob has problem detecting correct version. 
I'm using mrjob version 0.4.2 from pypi.
```
---
Name: mrjob
Version: 0.4.2
Location: /home/dgening/.venvs/garmr/lib/python2.7/site-packages
Requires: boto, PyYAML, simplejson
```

Here is my `$ hadoop version` output:
```
Hadoop 2.5.0-cdh5.2.0
Subversion Unknown -r Unknown
Compiled by kabu4i on 2015-02-18T13:25Z
Compiled with protoc 2.5.0
From source with checksum 46a824ffe3d85dee62905a23a7b7eb3
This command was run using /usr/local/share/hadoop/common/hadoop-common-2.5.0-cdh5.2.0.jar
```
I'm running job like this:
`sudo -u hadoop HADOOP_HOME=/usr/local/share/hadoop python src/mr/prepare.py -r hadoop --verbose logs/logs.txt`

STDERR Output:
```
looking for configs in /home/dgening/.mrjob.conf
looking for configs in /etc/mrjob.conf
no configs found; falling back on auto-configuration
looking for configs in /home/dgening/.mrjob.conf
looking for configs in /etc/mrjob.conf
no configs found; falling back on auto-configuration
Active configuration:
{'base_tmp_dir': '/tmp',
 'bootstrap_mrjob': True,
 'check_input_paths': True,
 'cleanup': ['ALL'],
 'cleanup_on_failure': ['NONE'],
 'cmdenv': {},
 'hadoop_bin': None,
 'hadoop_extra_args': [],
 'hadoop_home': '/usr/local/share/hadoop',
 'hadoop_streaming_jar': None,
 'hadoop_version': '0.20',
 'hdfs_scratch_dir': 'tmp/mrjob',
 'interpreter': ['python'],
 'jobconf': {'mapred.output.key.comparator.class': 'org.apache.hadoop.mapred.lib.KeyFieldBasedComparator',
             'mapred.text.key.comparator.options': '-k1',
             'mapred.text.key.partitioner.options': '-k1 -k2'},
 'label': None,
 'owner': 'hadoop',
 'python_archives': [],
 'python_bin': ['python'],
 'setup': [],
 'setup_cmds': [],
 'setup_scripts': [],
 'sh_bin': ['sh', '-e'],
 'steps_interpreter': ['/home/dgening/.venvs/garmr/bin/python'],
 'steps_python_bin': ['/home/dgening/.venvs/garmr/bin/python'],
 'upload_archives': [],
 'upload_files': []}
Looking for hadoop streaming jar in /usr/local/share/hadoop
Hadoop streaming jar is /usr/local/share/hadoop/tools/sources/hadoop-streaming-2.5.0-cdh5.2.0-sources.jar
creating tmp directory /tmp/prepare.hadoop.20150226.091910.387211
archiving /home/dgening/.venvs/garmr/lib/python2.7/site-packages/mrjob -> /tmp/prepare.hadoop.20150226.091910.387211/mrjob.tar.gz as mrjob/
writing wrapper script to /tmp/prepare.hadoop.20150226.091910.387211/setup-wrapper.sh
WRAPPER: # store $PWD
WRAPPER: __mrjob_PWD=$PWD
WRAPPER: 
WRAPPER: # obtain exclusive file lock
WRAPPER: exec 9>/tmp/wrapper.lock.prepare.hadoop.20150226.091910.387211
WRAPPER: python -c 'import fcntl; fcntl.flock(9, fcntl.LOCK_EX)'
WRAPPER: 
WRAPPER: # setup commands
WRAPPER: {
WRAPPER:   export PYTHONPATH=$__mrjob_PWD/mrjob.tar.gz:$PYTHONPATH
WRAPPER: } 0</dev/null 1>&2
WRAPPER: 
WRAPPER: # release exclusive file lock
WRAPPER: exec 9>&-
WRAPPER: 
WRAPPER: # run task from the original working directory
WRAPPER: cd $__mrjob_PWD
WRAPPER: "$@"
Making directory hdfs:///user/hadoop/tmp/mrjob/prepare.hadoop.20150226.091910.387211/files/ on HDFS
> /usr/local/share/hadoop/bin/hadoop fs -mkdir hdfs:///user/hadoop/tmp/mrjob/prepare.hadoop.20150226.091910.387211/files/
Traceback (most recent call last):
  File "src/mr/prepare.py", line 61, in <module>
    PrepareLog.run()
  File "/home/dgening/.venvs/garmr/lib/python2.7/site-packages/mrjob/job.py", line 494, in run
    mr_job.execute()
  File "/home/dgening/.venvs/garmr/lib/python2.7/site-packages/mrjob/job.py", line 512, in execute
    super(MRJob, self).execute()
  File "/home/dgening/.venvs/garmr/lib/python2.7/site-packages/mrjob/launch.py", line 147, in execute
    self.run_job()
  File "/home/dgening/.venvs/garmr/lib/python2.7/site-packages/mrjob/launch.py", line 208, in run_job
    runner.run()
  File "/home/dgening/.venvs/garmr/lib/python2.7/site-packages/mrjob/runner.py", line 458, in run
    self._run()
  File "/home/dgening/.venvs/garmr/lib/python2.7/site-packages/mrjob/hadoop.py", line 238, in _run
    self._upload_local_files_to_hdfs()
  File "/home/dgening/.venvs/garmr/lib/python2.7/site-packages/mrjob/hadoop.py", line 265, in _upload_local_files_to_hdfs
    self._mkdir_on_hdfs(self._upload_mgr.prefix)
  File "/home/dgening/.venvs/garmr/lib/python2.7/site-packages/mrjob/hadoop.py", line 273, in _mkdir_on_hdfs
    self.invoke_hadoop(['fs', '-mkdir', path])
  File "/home/dgening/.venvs/garmr/lib/python2.7/site-packages/mrjob/fs/hadoop.py", line 86, in invoke_hadoop
    proc = Popen(args, stdout=PIPE, stderr=PIPE)
  File "/usr/local/lib/python2.7/subprocess.py", line 709, in __init__
    errread, errwrite)
  File "/usr/local/lib/python2.7/subprocess.py", line 1326, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
As you can see variable ` 'hadoop_version': '0.20',`. 

Now weird stuff. Since for some reason i can't pdb through code for some reason I've runed few test.
I've grabbed regex from https://github.com/Yelp/mrjob/blob/master/mrjob/hadoop.py#L71
and tried to match output from `hadoop version`. Result is unexpected: 
```
> hv = re.compile(r'^.*?(?P<version>(\d|\.)+).*?$')
> m = hv.match('Hadoop 2.5.0-cdh5.2.0')
> hadoop_version = m.group('version')
> hadoop_version
'2.5.0'
> (mrjob.compat.version_gte(hadoop_version, "0.23") and not mrjob.compat.version_gte(hadoop_version, "0.24"))
False
ipdb> mrjob.compat.version_gte(hadoop_version, "2.0")
True
```

But even if i'm suppling version directly via `--hadoop-version=2.5.0`, `_mkdir_on_hdfs` is still running without `-p` option.

**Comment by dmgening** [comment]
Ok, nvm, just realised that fix wasn't implemented on 0.4.2
